In [1]:
import pandas as pd
import numpy as np
pd.options.display.max_columns = None
import datetime as dt
from datetime import date
from dateutil.relativedelta import relativedelta
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.style as style
style.use('fivethirtyeight')
import dataframe_image as dfi
import warnings
warnings.filterwarnings('ignore')

In [2]:
plt.rcParams['font.family'] = 'Nunito'
plt.rcParams['font.size'] = 10


color_code = ['#80ADF7','#EFBA50']
font_name = 'Nunito'
font_size = 10
font_size_title = 12
font_weight = 'bold'
orange_color = '#EFBA50'
blue_color = '#80ADF7'
grey_color = '#B0BCC8'
green_color = '#9EEDE0'
red_color = '#FD7284'
# color_code2 = [blue_color, grey_color]

background_color = "#F1F1F1"
border_color = "#B0BCC8"
text_align = 'center'
border_width ="0.5px"
border_style = 'solid'

body_design = { 'background' : "white", 'color' : 'black',  'border-color' : border_color, 'border-width' : border_width, 'border-style' : border_style,'font-family':font_name,'font-size':font_size,'text-align':text_align}
body_design2 = {'background' : "white", 'color' : 'black',  'border-color' : border_color, 'border-width' : border_width, 'border-style' : border_style,'font-family':font_name,'font-size':font_size,'text-align':text_align,'width':'70px'}
body_design3 = { 'background' : "white", 'color' : 'black',  'border-color' : border_color, 'border-width' : border_width, 'border-style' : border_style,'font-family':font_name,'font-size':font_size,'text-align':text_align,'width':'120px'}

border_design = {'selector': 'th', 'props': [('background-color' , background_color),('border-style' ,border_style),('font-family',font_name),('font-size',font_size),('border-width',border_width),('text-align',text_align),('border-color',border_color)]}
bar_width=0.5

In [3]:
%run operations_utils.py

In [4]:
%run path_changer_overall.py

In [5]:
# df = pd.read_csv(source_file_path+'rx_flow_data_july21_final_updated.csv')

In [6]:
# df['track_rx_recieved_new'] =  pd.to_datetime(df.track_erx_received, dayfirst = False)
# df['track_rx_entered_new'] =  pd.to_datetime(df.track_rx_entered, dayfirst = False)
# df['max_date'] = df[['track_rx_recieved_new','track_rx_entered_new']].max(axis=1)
# df['max_date_only'] = df['max_date'].dt.date
# df['pharmacy_loc'] = df['rx_code_key_location'].astype(str).str[0:5]

In [7]:
# six_months = date.today() - relativedelta(months=+6)
# six_months = six_months.strftime("%Y-%m")
# six_month_date = str(six_months)+"-01"
# six_month_date

In [8]:
# df['filled_datekey_new'] =  pd.to_datetime(df.filled_datekey, dayfirst = False)

In [9]:
# df = df[df['filled_datekey_new'] > six_month_date]

In [10]:
# df['times_processed_ibd_regular_new'] = df['times_processed_ibd_regular'].notnull()
# df['times_processed_ibd_2K_new'] = df['times_processed_ibd_2K'].notnull()

In [11]:
# df['mon_key'] = df['max_date'].dt.strftime('%m-%y')

# df['mon_key_2'] = df['max_date'].dt.strftime('%b-%y')

# # df = df[df['mon_key_2']!='Jul-21']

In [12]:
# df['trackrx_last_ibdtag_new'] = df['trackrx_last_ibdtag'].notnull()

In [13]:
# df['status_callforins_day01_new'] = df['status_callforins_day01'].notnull()

In [14]:
# df['times_processed_callforins_day02_new'] = df['times_processed_callforins_day02'].notnull()

In [15]:
# df['times_processed_callforins_day03_new'] = df['times_processed_callforins_day03'].notnull()

In [16]:
# #now apply all on scenario
# df['c1'] = pd.to_timedelta(df['time_consumed_callforins_day01'], errors = 'coerce')
# df['c2'] = pd.to_timedelta(df['time_consumed_callforins_day02'], errors = 'coerce')
# df['c3'] = pd.to_timedelta(df['time_consumed_callforins_day03'], errors = 'coerce')

In [17]:
# df['total_call'] = df[['c1','c2','c3']].sum(axis=1)

In [18]:
# def get_time_value(x):
#     return x > 0

In [19]:
# df['total_call_2'] = df['total_call'].dt.total_seconds()

In [20]:
# df['is_call'] = df['total_call_2'].apply(lambda x: get_time_value(x))

In [21]:
# pharmacy_loc_list = ['FL-MI', 'MD-BA', 'NC-RA', 'NJ-SO', 'NY-BK', 'NY-MA', 'PA-PH']
# df = df[df['pharmacy_loc'].isin(pharmacy_loc_list)]
# df.pharmacy_loc.unique()

In [22]:
%store -r main_odf_overall

In [23]:
df = main_odf_overall

In [24]:
df['trackrx_last_status_new'] = df['trackrx_last_status']
df['trackrx_last_status_new'] = df['trackrx_last_status_new'].replace(['F','T','U'], 'NB')
df['trackrx_last_status_new'] = df['trackrx_last_status_new'].replace(np.nan, 'B')

In [25]:
df['TOTALRXAMOUNT'] = df['TOTALRXAMOUNT'].astype(str)
df['TOTALRXAMOUNT'] = df['TOTALRXAMOUNT'].apply(lambda x: x.replace(',',''))
df['TOTALRXAMOUNT'] = df['TOTALRXAMOUNT'].astype(float)

In [26]:
df['rx_revenue'] = df['TOTALRXAMOUNT']

In [27]:
Rx_with_IBD_value_less_2k = df[(df['trackrx_last_ibdtag_new'] == True) & (df['times_processed_ibd_regular_new'] == True)]
Rx_with_IBD_value_greater_2k = df[(df['trackrx_last_ibdtag_new'] == True) & (df['times_processed_ibd_2K_new'] == True)]

In [28]:
# Rx_with_IBD_value_less_2k = df[(df['trackrx_last_ibdtag_new'] == True) & (df['status_callforins_day01_new'] == False) & (df['times_processed_ibd_regular_new'] == True)]

# Rx_with_IBD_2k = df[(df['trackrx_last_ibdtag_new'] == True) & (df['times_processed_ibd_regular_new'] == False) & (df['times_processed_ibd_2K_new'] == False) & (df['total_processing_time_ibd_new'] == False)]

# rx_list =  Rx_with_IBD_2k['rx_code_key_location'].to_list()

# # Rx_with_IBD2 = Rx_with_IBD[~Rx_with_IBD['rx_code_key_location'].isin(rx_list)]
# Rx_with_IBD_value_less_2k = Rx_with_IBD_value_less_2k[~Rx_with_IBD_value_less_2k['rx_code_key_location'].isin(rx_list)]

In [29]:
# Rx_with_IBD_value_greater_2k = df[(df['trackrx_last_ibdtag_new'] == True) & (df['status_callforins_day01_new'] == False) & (df['times_processed_ibd_2K_new'] == True)]


# Rx_with_IBD_value_greater_2k = Rx_with_IBD_value_greater_2k[~Rx_with_IBD_value_greater_2k['rx_code_key_location'].isin(rx_list)]

In [30]:
len(df)

322146

# Overall >2< level IBD for revenue and count

In [31]:
# Rx_with_IBD_value_less_2k_revenue_pivot

In [32]:
# Rx_with_IBD_value_less_2k billed
Rx_with_IBD_value_less_2k_billed = Rx_with_IBD_value_less_2k[Rx_with_IBD_value_less_2k['trackrx_last_status_new'] == 'B']

In [33]:
Rx_with_IBD_value_less_2k_count_pivot_billed = pd.pivot_table(Rx_with_IBD_value_less_2k_billed, values = ['rx_code_key_location'], index = ['pharmacy_loc'], aggfunc = 'count').reset_index()
Rx_with_IBD_value_less_2k_count_pivot_billed.rename(columns = {'rx_code_key_location':'Rx count for IBD < 2k', 'pharmacy_loc': 'Pharmacy loc'}, inplace = True)

Rx_with_IBD_value_less_2k_revenue_pivot_billed = pd.pivot_table(Rx_with_IBD_value_less_2k_billed, values = ['rx_revenue'], index = ['pharmacy_loc'], aggfunc = 'sum').reset_index()
Rx_with_IBD_value_less_2k_revenue_pivot_billed.rename(columns = {'rx_revenue':'Rx revenue for IBD < 2k($)', 'pharmacy_loc': 'Pharmacy loc'}, inplace = True)

In [34]:
# Rx_with_IBD_value_greater_2k_revenue_pivot

In [35]:
# Rx_with_IBD_value_greater_2k billed
Rx_with_IBD_value_greater_2k_billed = Rx_with_IBD_value_greater_2k[Rx_with_IBD_value_greater_2k['trackrx_last_status_new'] == 'B']

In [36]:
#Rx_with_IBD_value_greater_2k
Rx_with_IBD_value_greater_2k_count_pivot_billed = pd.pivot_table(Rx_with_IBD_value_greater_2k_billed, values = ['rx_code_key_location'], index = ['pharmacy_loc'], aggfunc = 'count').reset_index()
Rx_with_IBD_value_greater_2k_count_pivot_billed.rename(columns = {'rx_code_key_location':'Rx count for IBD > 2k', 'pharmacy_loc': 'Pharmacy loc'}, inplace = True)

Rx_with_IBD_value_greater_2k_revenue_pivot_billed = pd.pivot_table(Rx_with_IBD_value_greater_2k_billed, values = ['rx_revenue'], index = ['pharmacy_loc'], aggfunc = 'sum').reset_index()
Rx_with_IBD_value_greater_2k_revenue_pivot_billed.rename(columns = {'rx_revenue':'Rx revenue for IBD > 2k($)', 'pharmacy_loc': 'Pharmacy loc'}, inplace = True)

Rx_with_IBD_value_greater_2k_count_pivot_billed

  Pharmacy loc  Rx count for IBD > 2k
0        MD-BA                    101
1        NC-RA                     13
2        NJ-SO                     81
3        NY-BK                    312
4        NY-MA                     10
5        PA-PH                     89

In [37]:
Rx_count_IBD_less_and_greater_than_2k = pd.merge(Rx_with_IBD_value_less_2k_count_pivot_billed, Rx_with_IBD_value_greater_2k_count_pivot_billed, on = 'Pharmacy loc', how = 'left')
Rx_count_IBD_less_and_greater_than_2k = Rx_count_IBD_less_and_greater_than_2k.append(Rx_count_IBD_less_and_greater_than_2k.sum(axis=0), ignore_index = True)
Rx_count_IBD_less_and_greater_than_2k.iloc[[len(Rx_count_IBD_less_and_greater_than_2k)-1],[0]] = 'Overall'
Rx_count_IBD_less_and_greater_than_2k = Rx_count_IBD_less_and_greater_than_2k.set_index('Pharmacy loc')
Rx_count_IBD_less_and_greater_than_2k = Rx_count_IBD_less_and_greater_than_2k.replace(np.nan,0)
Rx_count_IBD_less_and_greater_than_2k = Rx_count_IBD_less_and_greater_than_2k[Rx_count_IBD_less_and_greater_than_2k.columns[:]].div(6,0).astype(int)
Rx_count_IBD_less_and_greater_than_2k

              Rx count for IBD < 2k  Rx count for IBD > 2k
Pharmacy loc
FL-MI                            86                      0
MD-BA                           127                     16
NC-RA                            87                      2
NJ-SO                           487                     13
NY-BK                           535                     52
NY-MA                            55                      1
PA-PH                           174                     14
Overall                        1553                    101

In [38]:
Rx_count_IBD_less_and_greater_than_2k['Total Count'] = Rx_count_IBD_less_and_greater_than_2k[['Rx count for IBD < 2k', 'Rx count for IBD > 2k']].sum(axis=1)
Rx_count_IBD_less_and_greater_than_2k

              Rx count for IBD < 2k  Rx count for IBD > 2k  Total Count
Pharmacy loc
FL-MI                            86                      0           86
MD-BA                           127                     16          143
NC-RA                            87                      2           89
NJ-SO                           487                     13          500
NY-BK                           535                     52          587
NY-MA                            55                      1           56
PA-PH                           174                     14          188
Overall                        1553                    101         1654

In [39]:
Rx_count_IBD_less_and_greater_than_2k['Rx count for IBD < 2k %'] = round(Rx_count_IBD_less_and_greater_than_2k['Rx count for IBD < 2k']/Rx_count_IBD_less_and_greater_than_2k['Total Count']*100,0).astype(int)
Rx_count_IBD_less_and_greater_than_2k['Rx count for IBD > 2k %'] = round(Rx_count_IBD_less_and_greater_than_2k['Rx count for IBD > 2k']/Rx_count_IBD_less_and_greater_than_2k['Total Count']*100,0).astype(int)
Rx_count_IBD_less_and_greater_than_2k

,Rx count for IBD < 2k,Rx count for IBD > 2k,Total Count,Rx count for IBD < 2k %,Rx count for IBD > 2k %
Pharmacy loc,,,,,
FL-MI,86,0,86,100,0
MD-BA,127,16,143,89,11
NC-RA,87,2,89,98,2
NJ-SO,487,13,500,97,3
NY-BK,535,52,587,91,9
NY-MA,55,1,56,98,2
PA-PH,174,14,188,93,7
Overall,1553,101,1654,94,6

In [40]:
Rx_count_IBD_less_and_greater_than_2k_final = Rx_count_IBD_less_and_greater_than_2k[['Total Count','Rx count for IBD < 2k', 'Rx count for IBD < 2k %', 'Rx count for IBD > 2k', 'Rx count for IBD > 2k %']]
#Rx_count_IBD_less_and_greater_than_2k_final = Rx_count_IBD_less_and_greater_than_2k_final.set_index('Pharmacy loc')
Rx_count_IBD_less_and_greater_than_2k_final = Rx_count_IBD_less_and_greater_than_2k_final.rename(columns = {'Rx count for IBD < 2k %': ' %', 'Rx count for IBD > 2k %': '% '})
Rx_count_IBD_less_and_greater_than_2k_final

,Total Count,Rx count for IBD < 2k,%,Rx count for IBD > 2k,%
Pharmacy loc,,,,,
FL-MI,86,86,100,0,0
MD-BA,143,127,89,16,11
NC-RA,89,87,98,2,2
NJ-SO,500,487,97,13,3
NY-BK,587,535,91,52,9
NY-MA,56,55,98,1,2
PA-PH,188,174,93,14,7
Overall,1654,1553,94,101,6

In [41]:
subset_value = (Rx_count_IBD_less_and_greater_than_2k_final.index.tolist()[:-1],['Rx count for IBD < 2k', 'Rx count for IBD > 2k'])

df_style1 = Rx_count_IBD_less_and_greater_than_2k_final.style.set_properties(**body_design).background_gradient(cmap='RdYlGn_r',axis=1, subset = subset_value).format("{:,}")
df_style1.set_table_styles([border_design])
df_style1

In [42]:
dfi.export(df_style1, ibd_images+'rx_count_ibd_less_and_greater_than_2k_final.png')

In [43]:
Rx_Revenue_IBD_less_and_greater_than_2k = pd.merge(Rx_with_IBD_value_less_2k_revenue_pivot_billed, Rx_with_IBD_value_greater_2k_revenue_pivot_billed, on = 'Pharmacy loc', how = 'left')
Rx_Revenue_IBD_less_and_greater_than_2k

  Pharmacy loc  Rx revenue for IBD < 2k($)  Rx revenue for IBD > 2k($)
0        FL-MI                   733199.08                         NaN
1        MD-BA                  1406941.64                   442298.93
2        NC-RA                   978091.54                    72871.67
3        NJ-SO                  4206348.30                   332410.32
4        NY-BK                  3678955.59                  1351954.19
5        NY-MA                   107575.22                     9107.78
6        PA-PH                  1772798.40                   274674.46

In [44]:
# revenue
Rx_Revenue_IBD_less_and_greater_than_2k = Rx_Revenue_IBD_less_and_greater_than_2k.append(Rx_Revenue_IBD_less_and_greater_than_2k.sum(axis = 0), ignore_index = True)
Rx_Revenue_IBD_less_and_greater_than_2k.iloc[[7],[0]] = 'Overall'
Rx_Revenue_IBD_less_and_greater_than_2k

  Pharmacy loc  Rx revenue for IBD < 2k($)  Rx revenue for IBD > 2k($)
0        FL-MI                   733199.08                         NaN
1        MD-BA                  1406941.64                   442298.93
2        NC-RA                   978091.54                    72871.67
3        NJ-SO                  4206348.30                   332410.32
4        NY-BK                  3678955.59                  1351954.19
5        NY-MA                   107575.22                     9107.78
6        PA-PH                  1772798.40                   274674.46
7      Overall                 12883909.77                  2483317.35

In [45]:
for i in Rx_Revenue_IBD_less_and_greater_than_2k.columns[1:]:
    Rx_Revenue_IBD_less_and_greater_than_2k = Rx_Revenue_IBD_less_and_greater_than_2k.replace(np.nan,0)
    Rx_Revenue_IBD_less_and_greater_than_2k[i] = Rx_Revenue_IBD_less_and_greater_than_2k[i].astype(int)

In [46]:
Rx_Revenue_IBD_less_and_greater_than_2k = Rx_Revenue_IBD_less_and_greater_than_2k.set_index('Pharmacy loc')
Rx_Revenue_IBD_less_and_greater_than_2k = Rx_Revenue_IBD_less_and_greater_than_2k[Rx_Revenue_IBD_less_and_greater_than_2k.columns[:]].div(6,0).astype(int)
Rx_Revenue_IBD_less_and_greater_than_2k

              Rx revenue for IBD < 2k($)  Rx revenue for IBD > 2k($)
Pharmacy loc
FL-MI                             122199                           0
MD-BA                             234490                       73716
NC-RA                             163015                       12145
NJ-SO                             701058                       55401
NY-BK                             613159                      225325
NY-MA                              17929                        1517
PA-PH                             295466                       45779
Overall                          2147318                      413886

In [47]:
Rx_Revenue_IBD_less_and_greater_than_2k['Total Revenue($)'] = Rx_Revenue_IBD_less_and_greater_than_2k[['Rx revenue for IBD < 2k($)', 'Rx revenue for IBD > 2k($)']].sum(axis=1)
Rx_Revenue_IBD_less_and_greater_than_2k

,Rx revenue for IBD < 2k($),Rx revenue for IBD > 2k($),Total Revenue($)
Pharmacy loc,,,
FL-MI,122199,0,122199
MD-BA,234490,73716,308206
NC-RA,163015,12145,175160
NJ-SO,701058,55401,756459
NY-BK,613159,225325,838484
NY-MA,17929,1517,19446
PA-PH,295466,45779,341245
Overall,2147318,413886,2561204

In [48]:
Rx_Revenue_IBD_less_and_greater_than_2k['Rx revenue for IBD < 2k %'] = round(Rx_Revenue_IBD_less_and_greater_than_2k['Rx revenue for IBD < 2k($)']/Rx_Revenue_IBD_less_and_greater_than_2k['Total Revenue($)']*100,0).astype(int)
Rx_Revenue_IBD_less_and_greater_than_2k['Rx revenue for IBD > 2k %'] = round(Rx_Revenue_IBD_less_and_greater_than_2k['Rx revenue for IBD > 2k($)']/Rx_Revenue_IBD_less_and_greater_than_2k['Total Revenue($)']*100,0).astype(int)
Rx_Revenue_IBD_less_and_greater_than_2k

,Rx revenue for IBD < 2k($),Rx revenue for IBD > 2k($),Total Revenue($),Rx revenue for IBD < 2k %,Rx revenue for IBD > 2k %
Pharmacy loc,,,,,
FL-MI,122199,0,122199,100,0
MD-BA,234490,73716,308206,76,24
NC-RA,163015,12145,175160,93,7
NJ-SO,701058,55401,756459,93,7
NY-BK,613159,225325,838484,73,27
NY-MA,17929,1517,19446,92,8
PA-PH,295466,45779,341245,87,13
Overall,2147318,413886,2561204,84,16

In [49]:
Rx_Revenue_IBD_less_and_greater_than_2k_final = Rx_Revenue_IBD_less_and_greater_than_2k[['Total Revenue($)', 'Rx revenue for IBD < 2k($)', 'Rx revenue for IBD < 2k %', 'Rx revenue for IBD > 2k($)', 'Rx revenue for IBD > 2k %']]
#Rx_Revenue_IBD_less_and_greater_than_2k_final = Rx_Revenue_IBD_less_and_greater_than_2k_final.set_index('Pharmacy loc')
Rx_Revenue_IBD_less_and_greater_than_2k_final = Rx_Revenue_IBD_less_and_greater_than_2k_final.rename(columns = {'Rx revenue for IBD < 2k %': ' %', 'Rx revenue for IBD > 2k %': '% '})
Rx_Revenue_IBD_less_and_greater_than_2k_final

,Total Revenue($),Rx revenue for IBD < 2k($),%,Rx revenue for IBD > 2k($),%
Pharmacy loc,,,,,
FL-MI,122199,122199,100,0,0
MD-BA,308206,234490,76,73716,24
NC-RA,175160,163015,93,12145,7
NJ-SO,756459,701058,93,55401,7
NY-BK,838484,613159,73,225325,27
NY-MA,19446,17929,92,1517,8
PA-PH,341245,295466,87,45779,13
Overall,2561204,2147318,84,413886,16

In [50]:
subset_value = (Rx_Revenue_IBD_less_and_greater_than_2k_final.index.tolist()[:-1],['Rx revenue for IBD < 2k($)', 'Rx revenue for IBD > 2k($)'])
df_style2 = Rx_Revenue_IBD_less_and_greater_than_2k_final.style.set_properties(**body_design).background_gradient(cmap='RdYlGn',axis=1, subset = subset_value).format("{:,}")
df_style2.set_table_styles([border_design])
df_style2

In [51]:
dfi.export(df_style2, ibd_images+'rx_revenue_ibd_less_and_greater_than_2k_final.png')

# IBD Denied

In [52]:
ibd_not_possible_list = ['IBD DENIED CALL MD TO SWITCH', 'IBD DENIED 2K+ (AMT)', 'IBD NOT POSSIBLE']

In [53]:
### Rx_with_IBD_value_less_2k

In [54]:
Rx_with_IBD_value_less_2k_denied = Rx_with_IBD_value_less_2k[Rx_with_IBD_value_less_2k['trackrx_last_ibdtag'].isin(ibd_not_possible_list)]

In [55]:
Rx_with_IBD_value_less_2k_denied

,Unnamed: 0,pharmacy_location,rxno,presnpi,ndc,trackrx_status,patientno,track_erx_received,track_rx_entered,rx_entered_date_verification,filled_datekey,final_rx_pickedup,rx_delivered_date,track_label_printed,final_rx_drug_picks,final_rx_rph_picks,last_run,rx_code_key_location,nabp,first_billed_datetime,end_billed_datetime,trackrx_processing_date_starttime,processing_end,IBD IN PROCESS,IBD FIDELIS,IBD REQUIRED,IBD $2K+,IBD IS $2K+,IBD 2K,IBD IS 2K,IBD SPECIALITY,IBD,IBD REGULAR,TO BE BILLED,CALL FOR INS,CALL FOR INS (KOREAN/CH),CALL FOR INS DAY 2,CALL FOR INS DAY 3,CALL FOR INS (KOREAN/CHINESE),CAL FOR INS (KOREAN/CHINESE),is_pickedup,is_eRx,trackrx_statusflow,trackrx_last_status,trackrx_last_delivery,trackrx_delivery_flow,trackrx_pickuptime_flow,trackrx_pickedup_flow,trackrx_last_pickuped,trackrx_last_ibdtag,trackrx_last_callinstag,end_filed_datetime,trackrx_callins_processing_start,ibd_processing_enddatetime,trackrx_ibd_processing_start,time_consumed_ibd_regular,times_processed_ibd_regular,status_ibd_regular,time_consumed_ibd_2K,times_processed_ibd_2K,status_ibd_2K,total_processing_time_ibd,times_processed_ibd,ibd_final_status,time_consumed_callforins_day01,times_processed_callforins_day01,status_callforins_day01,time_consumed_callforins_day02,times_processed_callforins_day02,status_callforins_day02,time_consumed_callforins_day03,times_processed_callforins_day03,status_callforins_day03,city,track_rx_filled,DRUGNAME,QTY,PATIENTCOPAY,TOTALINSPAID,PATZIP,PATDOB,INSCODE,DATEO,PATFNAME,PATLNAME,PATMOBILENO,PATPHONE,patsex,TOTALRXAMOUNT,patientno_mms,workflow_last_status,workflow_last_change_datetime,cxrev_last_datetime,times_cx_reversed,delrev_last_datetime,times_del_reversed,batchno,batchcreatedon,batchclosedon,deliverydate,driver,phone,patient_phone_x,batch_delivery_date,batch_delivery_datetime,batch_creation_datetime,batch_id,no_times_batch_created,delivery_date,shortId_of,status,patient_phone_y,patient_zipcode,delivery_time,Driver Number,didSucceed,match_method,rx_no_fill,zone_name,delivery_patient_zip_code,dl_app_delivery_created_time,dl_app_delivery_time,onfleet_short_id,delivery_id,driver_name,onfleet_state,pharmacy_location_dl,pharmacy_nabp,rx_no_fill_px,task_completed,slot_start,slot_end,pharmacy_location_px,refill_tag,new_delivered_date,PATPHONE_len,PATMOBILENO_len,shortId_mms,new_shortId,status_tag,id,rx_number,rx_status,patient_id,prescriber_id,insurance_id,drug_name,drug_form,followup_tag,copay,amount,ndc_prsc,quantity,fill_number,reversed,reversal_reason,reversal_fill_date,day_supply,status_prsc,created_at,id_task,status_id,associate_id_prsc,is_scheduled,scheduled_time,error_status,claimed_at,created_at_task,is_all_reversal_rxs,completed_at,cancelled_at,cancellation_reason,pharmacy_nabp_prsc,earliest_fill_date,rx_numbers_count,rx_numbers_list,total_awp,days_contacted,latest_contacted_at,insurance_category,parent_id,pharmacy_location_prsc,id_cv,contacted_at,outcome,created_at_cv,id_sd,payload,status_sd,created_at_sd,delivery_type,pickup_date_scheduled_deliveries,scheduled_startdate_scheduled_deliveries,scheduled_enddate_scheduled_deliveries,erxreceived_rxtimelines_boolean_d,rx_entered_date_rxtimelines_boolean_d,rx_entered_date_verification_boolean_d,rx_filledon_date_rxtimelines_boolean_d,rx_pickedup_date_rxtimelines_boolean_d,new_delivered_date_d_boolean_d,rx_labelprint_date_verification_boolean_d,rx_drugpick_date_verification_boolean_d,rx_rphpick_date_verification_boolean_d,first_billed_date_claimslog_boolean_d,last_billed_date_claimslog_boolean_d,processing_start_claimslog_boolean_d,processing_end_claimslog_boolean_d,current_status_rx_d,Overall_Visibility_for_Rx_d,erxreceived_rxtimelines_ltz_d,rx_entered_date_rxtimelines_ltz_d,first_billed_date_claimslog_ltz_d,last_billed_date_claimslog_ltz_d,rx_drugpick_date_verification_ltz_d,rx_rphpick_date_verification_ltz_d,pickup_date_scheduled_deliveries_ltz_d,scheduled_startdate_scheduled_deliveries_ltz_d,scheduled_enddate_scheduled_deliveries_ltz_d,new_delivered_date_ltz_d,created_at_contactevents_ltz_d,rx_filledon_date_rxtimelines_ltz_d,is_rescheduled_d,rescheduling_count_d,last_run,pharmacy_loc,filled_datekey_new,mon_key,mon_key_2,trackrx_last_ibdtag_new,status_callforins_day01_new,times_processed_ibd_new,status_ibd_2K_new,times_processed_ibd_regular_new,times_processed_ibd_2K_new,times_processed_callforins_day01_new,times_processed_callforins_day02_new,times_processed_callforins_day03_new,final_rx_entered,rx_delta,rx_delta_day,rx_delta_days_str,rx_delta_time2,ibd_processing_end_rx_final,received_to_entered_time,entered_to_first_billed,first_billed_to_last_billed,entered_to_last_billed,entered_to_label_printed,last_billed_to_label_printed,label_printed_to_drug_picked,drug_picked_to_rph_verified,rph_verified_to_pharmacy_pickedup,rph_verified_to_batch_creation,batch_creation_to_delivered,rph_verified_to_delivered,ibd_processing_start_to_end,time_to_identify_pa_is_required,waiting_time_for_ibd_processing,ibd_processing_end_to_label_printed,rx_entered_to_callins_processing_start,ibd_processing_end_to_first_billed,rph_verified_to_delivery_pickedup,delivery_pickedup_to_delivered,final_received_to_delivered,received_to_rph_verified,time_taken_by_rx_to_be_picked_up_by_IBD_team,time_taken_by_IBD_team_to_process_rx,c1,c2,c3,total_call,time_taken_for_call_for_insurance_process,total_call_2,is_call,total_processing_time_ibd_new,trackrx_last_status_new,rx_revenue
424,424,MD-BA,200821-1,1205834397,75987002201,F,11552,NaT,2021-09-21 17:15:00,2021-09-21 17:15:00,2021-10-26 17:14:54,NaT,NaN,NaT,NaT,NaT,2022-01-09 01:21:07,MD-BA-200821-1,2143674.0,NaT,NaT,2021-09-21 17:14:59,2022-01-08 12:24:14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-10-13 15:24:03,NaN,2021-10-06 12:00:55,2021-10-06 12:00:39,NaN,NaN,NaN,NaN,NaN,NaN,False,U->F,F,NaN,NaN,NaN,NaN,NaN,IBD NOT POSSIBLE,TO BE BILLED,2021-10-26 09:33:53,2021-10-06 12:00:39,NaT,2021-10-13 13:54:29,0 days 01:29:34,1.0,completed,NaT,NaN,NaN,NaT,NaN,NaN,0 days 00:00:16,1.0,completed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Refill,NaT,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True,True,True,False,False,False,False,False,False,False,True,True,1100,Rx with IBD and CFI both,NaN,2021-09-21 13:15:00-04:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-10-26 13:14:54-04:00,NaN,NaN,2022-01-10 06:31:22,MD-BA,2021-10-26 17:14:54,10-21,Oct-21,True,True,False,False,True,False,True,False,False,2021-09-21 17:15:00,0 days 01:29:34,0 days,days,0 days 01:29:34,2021-10-13 15:24:03,NA,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NA,NA,NA,NA,NaT,21 days 20:39:29,NaT,NaT,14 days 18:45:39,NaT,NA,NA,NaT,NaT,NaT,NaT,0 days 00:00:16,NaT,NaT,0 days 00:00:16,0 days 00:00:16,16.0,True,False,NB,NaN
2586,2586,NY-MA,923960-0,1659869956,00299595030,F,74161,2021-10-12 09:10:00,2021-10-12 00:00:00,2021-10-12 11:51:00,2021-10-12 00:00:00,NaT,NaN,NaT,NaT,NaT,2022-01-07 01:20:41,NY-MA-923960-0,3308055.0,NaT,NaT,2021-10-12 11:51:26,2022-01-06 14:20:39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-10-22 10:22:58,NaN,2021-10-12 11:53:26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,U->F,F,NaN,NaN,NaN,->N,N,IBD NOT POSSIBLE,NaN,2021-12-30 18:55:41,NaT,NaT,2021-10-12 16:35:32,0 days 20:20:44,1.0,completed,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,NaT,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,False,False,False,False,False,False,False,True,True,11100,Rx with only IBD,2021-10-12 05:10:00-04:00,2021-10-11 20:00:00-04:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-10-11 20:00:00-04:00,NaN,NaN,2022-01-10 06:31:22,NY-MA,2021-10-12 00:00:00,10-21,Oct-21,True,False,False,False,True,False,False,False,False,2021-10-12 00:00:00,0 days 20:20:44,0 days,days,0 days 20:20:44,2021-10-13 12:56:16,-1 days +14:50:00,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NA,NA,NA,NA,NaT,0 days 16:35:32,NaT,NaT,NaT,NaT,NA,NA,NaT,NaT,NaT,NaT,NaT,NaT,NaT,0 days 00:00:00,0 days 00:00:00,0.0,False,False,NB,NaN
2872,2872,FL-MI,776012-0,1356552178,00187540004,B,22472,2021-10-14 15:06:00,2021-10-15 11:23:00,2021-10-15 11:23:00,2021-10-19 11:22:41,2021-10-22,2021-10-22 12:42:57,2021-10-20 12:54:31,2021-10-19 16:45:00,2021-10-19 17:12:57,2022-01-07 01:20:41,FL-MI-776012-0,5744859.0,2021-10-19 16:40:39,2021-10-19 16:40:39,2021-10-15 11:22:56,2022-01-06 15:08:22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-10-18 10:43:59,NaN,2021-10-15 11:22:56,NaN,NaN,NaN,NaN,NaN,NaN,False,True,U->B,B,D,None->D,None->12:42 PM,->Y,Y,IBD NOT POSSIBLE,NaN,NaT,NaT,NaT,2021-10-15 17:36:29,2 days 17:07:30,1.0,completed,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MIAMI,2021-10-19,JUBLIA 10% SOL (00187-5400-04) -8134902,4.0,65.0,570.33,33134.0,07-13-1957,FLB68,2021-10-14,SILVIA,VIDAL,,3057854186,F,635.33,22472.0,PICKED UP/DELIVERED,2021-10-25 15:23:26,NaT,NaN,NaT,NaN,BN2110210006,2021-10-21 13:31:00,NaN,NaN,JCU,(305)785-4186,3057854186,2021-10-21,2021-10-21 13:31:00,2021-10-21 13:31:00,BN2110210006,1.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,2021-10-22 12:42:57,10,10,NaN,NaN,Delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,False,True,True,True,True,True,True,True,True,11101,Rx with only IBD,2021-10-14 11:06:00-04:00,2021-10-15 07:23:00-04:00,2021-10-19 12:40:39-04:00,2021-10-19 12:40:39-04:00,2021-10-19 12:45:00-04:00,2021-10-19 13:12:57-04:00,NaN,NaN,NaN,2021-10-22 08:42:57-04:00,NaN,2021-10-19 07:22:41-04:00,NaN,NaN,2022-01-10 06:31:22,FL-MI,2021-10-19 11:22:41,10-21,Oct-21,True,False,False,False,True,False,False,False,False,2021-10-15 11:23:00,2 days 17:07:30,2 days,days,0 days 17:07:30,2021-10-18 10:43:59,0 days 20:17:00,4 days 05:17:39,0 days,4 days 05:17:39,5 days 01:31:31,0 days 20:13:52,-1 days +03:50:29,0 days 00:27:57,NA,1 days 20:18:03,0 days 23:11:57,2 days 19:30:00,NaT,0 days 06:13:29,NaT,NaT,NaT,1 days 05:56:40,2 days 06:47:03,0 days 12:42:57,7 days 01:19:57,5 days 02:06:57,NaT,NaT,NaT,NaT,NaT,0 days 00:00:00,0 days 00:00:00,0.0,False,False,B,635.33
3028,3028,NY-MA,926190-0,1023084696,00187511045,F,74438,NaT,2021-11-11 00:00:00,NaN,2021-11-11 00:00:00,NaT,NaN,NaT,NaT,NaT,2022-01-07 01:20:41,NY-MA-926190-0,3308055.0,NaT,NaT,2021-11-12 12:01:15,2022-01-06 14:32:40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-04 08:43:16,NaN,2021-12-30 12:33:06,2021-12-30 12:27:43,NaN,2021-12-30 12:27:43,NaN,NaN,NaN,NaN,False,U->F,F,NaN,NaN,NaN,->N,N,IBD NOT POSSIBLE,TO BE BILLED,2022-01-06 14:29:39,2021-12-15 18:24:08,NaT,2022-01-03 16:39:13,0 days 16:04:03,1.0,completed,NaT,NaN,NaN,NaT,NaN,NaN,14 days 18:03:35,1.0,completed,0 days 00:05:23,1.0,completed,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,NaT,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True,False,True,False,False,False,False,False,False,False,True,True,1100,Rx with IBD and CFI both,NaN,2021-11-10 19:00:00-05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-10 19:00:00-05:00,NaN,NaN,2022-01-10 06:31:22,NY-MA,2021-11-11 00:00:00,11-21,Nov-21,True,True,False,False,True,False,True,True,False,2021-11-11 00:00:00,0 days 16:04:03,0 days,days,0 days 16:04:03,2022-01-04 08:43:16,NA,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NA,NA,NA,NA,NaT,53 days 16:39:13,NaT,NaT,34 days 18:24:08,NaT,NA,NA,NaT,NaT,NaT,NaT,14 days 18:03:35,0 days 00:05:23,NaT,14 days 18:08:58,14 days 18:08:58,1274938.0,True,False,NB,NaN
3129,3129,NY-MA,928798-0,1770974610,00591352530,F,71354,2021-12-20 13:11:00,2021-12-20 00:00:00,2021-12-20 13:41:00,2021-12-20 00:00:00,NaT,NaN,NaT,NaT,NaT,2022-01-07 01:20:41,NY-MA-928798-0,3308055.0,NaT,NaT,2021-12-20 13:41:09,2022-01-06 13:56:39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-20 16:06:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,U->F,F,NaN,NaN,NaN,->N,N,IBD NOT POSSIBLE,NaN,2021-12-30 21:08:45,NaT,NaT,2021-12-20 13:41:09,0 days 02:24:51,1.0,completed,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,NaT,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,False,False,False,False,False,False,False,True,True,11100,Rx with only IBD,2021-12-20 08:11:00-05:00,2021-12-19 19:00:00-05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-19 19:00:00-05:00,NaN,NaN,2022-01-10 06:31:22,NY-MA,2021-12-20 00:00:00,12-21,Dec-21,True,False,False,False,True,False,False,False,False,2021-12-20 00:00:00,0 days 02:24:51,0 days,days,0 days 02:24:51,2021-12-20 16:06:00,-1 days +10:49:00,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NA,NA,NA,NA,NaT,0 days 13:41:09,NaT,NaT,NaT,NaT,NA,NA,NaT,NaT,NaT,NaT,NaT,NaT,NaT,0 days 00:00:00,0 days 00:00:00,0.0,False,False,NB,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363455,363455,NY-MA,925637-0,1144516121.0,70727052925,F,73961,NaT,2021-11-02 17:18:00,NaN,2021-11-03 00:00:00,NaT,NaN,2021-11-03 14:02:25,NaT,NaT,2022-01-05 01:20:44,NY-MA-925637-0,3308055.0,NaT,NaT,2021-11-03 14:01:58,2022-01-05 03:57:24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-15 09:53:48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,U->F,F,NaN,NaN,NaN,->N,N,IBD NOT POSSIBLE,NaN,2022-01-04 21:06:12,NaT,NaT,2021-11-03 14:02:05,0 days 21:51:26,1.0,completed,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,NaT,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True,False,True,False,False,True,False,False,False,False,True,True,1100,Rx with only IBD,NaN,2021-11-02 13:18:00-04:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-02 20:00:00-04:00,NaN,NaN,2022-01-07 06:24:48,NY-MA,2021-11-03 00:00:00,11-21,Nov-21,True,False,False,False,True,False,False,False,False,2021-11-02 17:18:00,0 days 21:51:26,0 days,days,0 days 21:51:26,2021-11-04 11:53:31,NA,NaT,NaT,NaT,0 days 20:44:25,NaT,NaT,NaT,NA,NA,NA,NA,NaT,0 days 20:44:05,NaT,NaT,NaT,NaT,NA,NA,NaT,NaT,NaT,NaT,NaT,NaT,NaT,0 days 00:00:00,0 days 00:00:00,0.0,False,False,NB,NaN
363513,363513,NY-MA,925902-0,1497199202.0,45802043733,F,72232,2021-11-08 11:14:00,2021-11-08 00:00:00,2021-11-08 15:10:00,2021-11-08 00:00:00,NaT,NaN,NaT,NaT,NaT,2022-01-05 01:20:44,NY-MA-925902-0,3308055.0,2021-12-20 09:46:07,2021-12-20 09:46:07,2021-11-08 15:09:50,2022-01-05 03:57:24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-16 16:16:26,2021-11-11 12:42:07,2021-11-08 15:09:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,U->B->U->F,F,NaN,NaN,NaN,->N,N,IBD NOT POSSIBLE,NaN,2021-12-30 22:36:42,NaT,NaT,2021-11-08 17:23:22,5 days 21:53:42,2.0,completed,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,NaT,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,False,False,False,False,False,True,True,True,True,11100,Rx with only IBD,2021-11-08 06:14:00-05:00,2021-11-07 19:00:00-05:00,2021-12-20 04:46:07-05:00,2021-12-20 04:46:07-05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-07 19:00:00-05:00,NaN,NaN,2022-01-07 06:24:48,NY-MA,2021-11-08 00:00:00,11-21,Nov-21,True,False,False,False,True,False,False,False,False,2021-11-08 00:00:00,5 days 21:53:42,5 days,days,0 days 21:53:42,2021-11-14 15:17:04,-1 days +12:46:00,42 days 09:46:07,0 days,42 days 09:46:07,NaT,NaT,NaT,NaT,NA,NA,NA,NA,NaT,0 days 17:23:22,NaT,NaT,NaT,35 days 18:29:03,NA,NA,NaT,NaT,NaT,NaT,NaT,NaT,NaT,0 days 00:00:00,0 days 00:00:00,0.0,False,False,NB,NaN

In [56]:
Rx_with_IBD_value_less_2k_denied_count_pivot = pd.pivot_table(Rx_with_IBD_value_less_2k_denied, values = ['rx_code_key_location'], index = ['pharmacy_loc'], aggfunc = 'count').reset_index()
Rx_with_IBD_value_less_2k_denied_count_pivot.rename(columns = {'rx_code_key_location':'rx_count_IBD_Denied'}, inplace = True)
Rx_with_IBD_value_less_2k_denied_count_pivot

  pharmacy_loc  rx_count_IBD_Denied
0        FL-MI                  103
1        MD-BA                  612
2        NC-RA                    7
3        NJ-SO                   67
4        NY-BK                  153
5        NY-MA                  120
6        PA-PH                  223

In [57]:
Rx_with_IBD_value_less_2k_denied_revenue_pivot = pd.pivot_table(Rx_with_IBD_value_less_2k_denied, values = ['rx_revenue'], index = ['pharmacy_loc'], aggfunc = 'sum').reset_index()
Rx_with_IBD_value_less_2k_denied_revenue_pivot.rename(columns = {'rx_revenue':'rx_revenue_IBD_Denied'}, inplace = True)
Rx_with_IBD_value_less_2k_denied_revenue_pivot

  pharmacy_loc  rx_revenue_IBD_Denied
0        FL-MI               12487.93
1        MD-BA                6724.63
2        NC-RA                   0.00
3        NJ-SO                3508.00
4        NY-BK               18342.40
5        NY-MA                   0.00
6        PA-PH               38254.54

In [58]:
Rx_with_IBD_value_less_2k_denied_pivot = pd.merge(Rx_with_IBD_value_less_2k_denied_count_pivot, Rx_with_IBD_value_less_2k_denied_revenue_pivot, on='pharmacy_loc', how='left')
Rx_with_IBD_value_less_2k_denied_pivot

  pharmacy_loc  rx_count_IBD_Denied  rx_revenue_IBD_Denied
0        FL-MI                  103               12487.93
1        MD-BA                  612                6724.63
2        NC-RA                    7                   0.00
3        NJ-SO                   67                3508.00
4        NY-BK                  153               18342.40
5        NY-MA                  120                   0.00
6        PA-PH                  223               38254.54

In [59]:
Rx_with_IBD_value_less_2k_denied_pivot.append(Rx_with_IBD_value_less_2k_denied_pivot.sum(axis=0), ignore_index=True).to_clipboard(index=False)

In [60]:
### Rx_with_IBD_value_greater_2k_denied

In [61]:
Rx_with_IBD_value_greater_2k_denied = Rx_with_IBD_value_greater_2k[Rx_with_IBD_value_greater_2k['trackrx_last_ibdtag'].isin(ibd_not_possible_list)]

#Rx_with_IBD_value_greater_2k_IBD_df['IBD_status'] = Rx_with_IBD_value_greater_2k_IBD_df

In [62]:
Rx_with_IBD_value_greater_2k_denied

,Unnamed: 0,pharmacy_location,rxno,presnpi,ndc,trackrx_status,patientno,track_erx_received,track_rx_entered,rx_entered_date_verification,filled_datekey,final_rx_pickedup,rx_delivered_date,track_label_printed,final_rx_drug_picks,final_rx_rph_picks,last_run,rx_code_key_location,nabp,first_billed_datetime,end_billed_datetime,trackrx_processing_date_starttime,processing_end,IBD IN PROCESS,IBD FIDELIS,IBD REQUIRED,IBD $2K+,IBD IS $2K+,IBD 2K,IBD IS 2K,IBD SPECIALITY,IBD,IBD REGULAR,TO BE BILLED,CALL FOR INS,CALL FOR INS (KOREAN/CH),CALL FOR INS DAY 2,CALL FOR INS DAY 3,CALL FOR INS (KOREAN/CHINESE),CAL FOR INS (KOREAN/CHINESE),is_pickedup,is_eRx,trackrx_statusflow,trackrx_last_status,trackrx_last_delivery,trackrx_delivery_flow,trackrx_pickuptime_flow,trackrx_pickedup_flow,trackrx_last_pickuped,trackrx_last_ibdtag,trackrx_last_callinstag,end_filed_datetime,trackrx_callins_processing_start,ibd_processing_enddatetime,trackrx_ibd_processing_start,time_consumed_ibd_regular,times_processed_ibd_regular,status_ibd_regular,time_consumed_ibd_2K,times_processed_ibd_2K,status_ibd_2K,total_processing_time_ibd,times_processed_ibd,ibd_final_status,time_consumed_callforins_day01,times_processed_callforins_day01,status_callforins_day01,time_consumed_callforins_day02,times_processed_callforins_day02,status_callforins_day02,time_consumed_callforins_day03,times_processed_callforins_day03,status_callforins_day03,city,track_rx_filled,DRUGNAME,QTY,PATIENTCOPAY,TOTALINSPAID,PATZIP,PATDOB,INSCODE,DATEO,PATFNAME,PATLNAME,PATMOBILENO,PATPHONE,patsex,TOTALRXAMOUNT,patientno_mms,workflow_last_status,workflow_last_change_datetime,cxrev_last_datetime,times_cx_reversed,delrev_last_datetime,times_del_reversed,batchno,batchcreatedon,batchclosedon,deliverydate,driver,phone,patient_phone_x,batch_delivery_date,batch_delivery_datetime,batch_creation_datetime,batch_id,no_times_batch_created,delivery_date,shortId_of,status,patient_phone_y,patient_zipcode,delivery_time,Driver Number,didSucceed,match_method,rx_no_fill,zone_name,delivery_patient_zip_code,dl_app_delivery_created_time,dl_app_delivery_time,onfleet_short_id,delivery_id,driver_name,onfleet_state,pharmacy_location_dl,pharmacy_nabp,rx_no_fill_px,task_completed,slot_start,slot_end,pharmacy_location_px,refill_tag,new_delivered_date,PATPHONE_len,PATMOBILENO_len,shortId_mms,new_shortId,status_tag,id,rx_number,rx_status,patient_id,prescriber_id,insurance_id,drug_name,drug_form,followup_tag,copay,amount,ndc_prsc,quantity,fill_number,reversed,reversal_reason,reversal_fill_date,day_supply,status_prsc,created_at,id_task,status_id,associate_id_prsc,is_scheduled,scheduled_time,error_status,claimed_at,created_at_task,is_all_reversal_rxs,completed_at,cancelled_at,cancellation_reason,pharmacy_nabp_prsc,earliest_fill_date,rx_numbers_count,rx_numbers_list,total_awp,days_contacted,latest_contacted_at,insurance_category,parent_id,pharmacy_location_prsc,id_cv,contacted_at,outcome,created_at_cv,id_sd,payload,status_sd,created_at_sd,delivery_type,pickup_date_scheduled_deliveries,scheduled_startdate_scheduled_deliveries,scheduled_enddate_scheduled_deliveries,erxreceived_rxtimelines_boolean_d,rx_entered_date_rxtimelines_boolean_d,rx_entered_date_verification_boolean_d,rx_filledon_date_rxtimelines_boolean_d,rx_pickedup_date_rxtimelines_boolean_d,new_delivered_date_d_boolean_d,rx_labelprint_date_verification_boolean_d,rx_drugpick_date_verification_boolean_d,rx_rphpick_date_verification_boolean_d,first_billed_date_claimslog_boolean_d,last_billed_date_claimslog_boolean_d,processing_start_claimslog_boolean_d,processing_end_claimslog_boolean_d,current_status_rx_d,Overall_Visibility_for_Rx_d,erxreceived_rxtimelines_ltz_d,rx_entered_date_rxtimelines_ltz_d,first_billed_date_claimslog_ltz_d,last_billed_date_claimslog_ltz_d,rx_drugpick_date_verification_ltz_d,rx_rphpick_date_verification_ltz_d,pickup_date_scheduled_deliveries_ltz_d,scheduled_startdate_scheduled_deliveries_ltz_d,scheduled_enddate_scheduled_deliveries_ltz_d,new_delivered_date_ltz_d,created_at_contactevents_ltz_d,rx_filledon_date_rxtimelines_ltz_d,is_rescheduled_d,rescheduling_count_d,last_run,pharmacy_loc,filled_datekey_new,mon_key,mon_key_2,trackrx_last_ibdtag_new,status_callforins_day01_new,times_processed_ibd_new,status_ibd_2K_new,times_processed_ibd_regular_new,times_processed_ibd_2K_new,times_processed_callforins_day01_new,times_processed_callforins_day02_new,times_processed_callforins_day03_new,final_rx_entered,rx_delta,rx_delta_day,rx_delta_days_str,rx_delta_time2,ibd_processing_end_rx_final,received_to_entered_time,entered_to_first_billed,first_billed_to_last_billed,entered_to_last_billed,entered_to_label_printed,last_billed_to_label_printed,label_printed_to_drug_picked,drug_picked_to_rph_verified,rph_verified_to_pharmacy_pickedup,rph_verified_to_batch_creation,batch_creation_to_delivered,rph_verified_to_delivered,ibd_processing_start_to_end,time_to_identify_pa_is_required,waiting_time_for_ibd_processing,ibd_processing_end_to_label_printed,rx_entered_to_callins_processing_start,ibd_processing_end_to_first_billed,rph_verified_to_delivery_pickedup,delivery_pickedup_to_delivered,final_received_to_delivered,received_to_rph_verified,time_taken_by_rx_to_be_picked_up_by_IBD_team,time_taken_by_IBD_team_to_process_rx,c1,c2,c3,total_call,time_taken_for_call_for_insurance_process,total_call_2,is_call,total_processing_time_ibd_new,trackrx_last_status_new,rx_revenue
7260,7260,MD-BA,208893-0,1619210598,00024591502,F,15396,2021-09-30 10:38:00,2021-09-30 11:12:00,2021-09-30 11:12:00,2021-10-19 11:11:48,NaT,NaN,NaT,NaT,NaT,2022-01-11 01:20:42,MD-BA-208893-0,2143674.0,NaT,NaT,2021-09-30 11:13:24,2022-01-10 15:38:44,2021-10-15 11:13:41,NaN,NaN,NaN,NaN,NaN,NaN,2021-10-04 16:07:39,2021-10-19 10:13:38,2021-10-04 16:00:19,2021-09-30 11:13:28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,U->F,F,NaN,NaN,NaN,->N,N,IBD DENIED CALL MD TO SWITCH,NaN,2021-10-19 10:25:18,NaT,2021-10-19 10:13:38,2021-09-30 13:06:25,0 days 00:23:20,3.0,completed,2 days 17:52:44,2.0,completed,12 days 20:11:24,3.0,completed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,NaT,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,False,False,False,False,False,False,False,True,True,11100,Rx with only IBD,2021-09-30 06:38:00-04:00,2021-09-30 07:12:00-04:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-10-19 07:11:48-04:00,NaN,NaN,2022-01-12 06:36:51,MD-BA,2021-10-19 11:11:48,10-21,Oct-21,True,False,True,True,True,True,False,False,False,2021-09-30 11:12:00,15 days 14:27:28,15 days,days,0 days 14:27:28,2021-10-16 03:33:53,0 days 00:34:00,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NA,NA,NA,NA,-19 days +02:52:47,0 days 01:54:25,18 days 21:07:13,NaT,NaT,NaT,NA,NA,NaT,NaT,2 days 18:16:04,12 days 20:11:24,NaT,NaT,NaT,0 days 00:00:00,0 days 00:00:00,0.0,False,True,NB,NaN
12432,12432,NJ-SO,1162638-0,1417203928.0,55513013760,F,66496,NaT,2021-05-21 12:17:00,2021-05-21 12:17:00,2021-12-29 00:00:00,NaT,NaN,NaT,NaT,NaT,2021-12-30 01:21:17,NJ-SO-1162638-0,3135868.0,NaT,NaT,2021-05-21 12:14:26,2021-12-29 15:12:35,2021-06-21 10:47:12,NaN,NaN,NaN,NaN,NaN,NaN,2021-05-21 12:17:37,2021-12-29 14:20:49,NaN,NaN,2021-05-21 12:14:26,NaN,NaN,NaN,NaN,NaN,NaN,False,U->F,F,NaN,NaN,NaN,->N,N,IBD DENIED 2K+ (AMT),IBD SPECIALITY,2021-12-29 15:12:34,2021-05-21 12:14:26,2021-06-21 16:32:12,2021-05-21 12:17:37,NaT,NaN,exception,30 days 22:29:35,1.0,completed,0 days 05:45:00,1.0,completed,0 days 00:03:11,1.0,completed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,NaT,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True,True,True,False,False,False,False,False,False,False,True,True,1100,Rx with IBD and CFI both,NaN,2021-05-21 08:17:00-04:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-28 19:00:00-05:00,NaN,NaN,2021-12-31 06:31:20,NJ-SO,2021-12-29 00:00:00,12-21,Dec-21,True,True,True,True,False,True,True,False,False,2021-05-21 12:17:00,31 days 04:14:35,31 days,days,0 days 04:14:35,2021-06-21 16:32:12,NA,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NA,NA,NA,NA,-32 days +19:45:25,0 days 00:00:37,31 days 04:14:35,NaT,-1 days +23:57:26,NaT,NA,NA,NaT,NaT,NaT,0 days 05:45:00,0 days 00:03:11,NaT,NaT,0 days 00:03:11,0 days 00:03:11,191.0,True,True,NB,NaN
13217,13217,NY-BK,1143607-0,1477711422.0,00024591502,F,618509,2021-10-29 11:12:00,2021-10-29 11:17:00,2021-10-29 11:17:00,2021-12-06 11:16:40,NaT,NaN,NaT,NaT,NaT,2021-12-20 01:23:58,NY-BK-1143607-0,3352779.0,NaT,NaT,2021-10-29 11:18:48,2021-12-29 15:53:09,2021-10-29 16:12:12,NaN,NaN,NaN,NaN,NaN,NaN,2021-10-29 12:04:54,2021-11-05 15:35:37,NaN,2021-10-29 11:18:49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,U->F,F,NaN,NaN,NaN,->N,N,IBD DENIED CALL MD TO SWITCH,NaN,2021-12-06 19:11:06,NaT,2021-11-05 15:35:37,2021-10-29 11:54:00,0 days 00:10:54,1.0,completed,0 days 00:26:50,1.0,completed,6 days 23:23:25,1.0,completed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,NaT,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,False,False,False,False,False,False,False,True,True,11100,Rx with only IBD,2021-10-29 07:12:00-04:00,2021-10-29 07:17:00-04:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-06 06:16:40-05:00,NaN,NaN,2021-12-31 06:31:20,NY-BK,2021-12-06 11:16:40,12-21,Dec-21,True,False,True,True,True,True,False,False,False,2021-10-29 11:17:00,7 days 00:01:09,7 days,days,0 days 00:01:09,2021-11-05 11:55:09,0 days 00:05:00,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NA,NA,NA,NA,-8 days +20:18:23,0 days 00:37:00,7 days 03:41:37,NaT,NaT,NaT,NA,NA,NaT,NaT,0 days 00:37:44,6 days 23:23:25,NaT,NaT,NaT,0 days 00:00:00,0 days 00:00:00,0.0,False,True,NB,NaN
14975,14975,MD-BA,209365-0,1669929451.0,70539000102,F,15603,NaT,2021-10-11 11:04:00,2021-10-11 11:04:00,2021-11-19 11:03:39,NaT,NaN,NaT,NaT,NaT,2021-11-20 01:20:21,MD-BA-209365-0,2143674.0,NaT,NaT,2021-10-11 11:14:37,2021-11-19 16:33:57,2021-10-28 10:38:30,NaN,NaN,NaN,NaN,NaN,NaN,2021-10-12 09:22:36,2021-10-28 12:15:38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,U->F,F,NaN,NaN,NaN,->N,N,IBD NOT POSSIBLE,NaN,2021-11-18 17:01:48,NaT,2021-10-28 12:15:39,2021-10-11 11:14:47,0 days 01:29:12,1.0,completed,0 days 04:18:15,1.0,completed,6 days 22:12:23,2.0,completed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,NaT,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True,True,True,False,False,False,False,False,False,False,True,True,1100,Rx with only IBD,NaN,2021-10-11 07:04:00-04:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-19 06:03:39-05:00,NaN,NaN,2021-12-21 03:36:15,MD-BA,2021-11-19 11:03:39,11-21,Nov-21,True,False,True,True,True,True,False,False,False,2021-10-11 11:04:00,7 days 03:59:50,7 days,days,0 days 03:59:50,2021-10-18 15:14:37,NA,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NA,NA,NA,NA,-18 days +22:59:08,0 days 00:10:47,17 days 01:00:52,NaT,NaT,NaT,NA,NA,NaT,NaT,0 days 05:47:27,6 days 22:12:23,NaT,NaT,NaT,0 days 00:00:00,0 days 00:00:00,0.0,False,True,NB,NaN
16826,16826,MD-BA,209158-0,1528254232.0,65649030302,F,15513,2021-10-05 16:36:00,2021-10-05 16:41:00,2021-10-05 16:41:00,2021-10-22 16:40:36,NaT,NaN,NaT,NaT,NaT,2021-10-23 01:20:49,MD-BA-209158-0,2143674.0,NaT,NaT,2021-10-05 16:41:14,2021-10-22 09:30:54,2021-10-14 11:22:54,NaN,NaN,NaN,NaN,NaN,NaN,2021-10-14 11:17:59,2021-10-18 16:05:07,NaN,2021-10-05 16:41:34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,U->F,F,NaN,NaN,NaN,->N,N,IBD DENIED CALL MD TO SWITCH,NaN,2021-10-22 09:30:54,NaT,2021-10-18 16:05:08,2021-10-06 09:20:55,0 days 01:22:06,1.0,completed,0 days 00:04:55,1.0,completed,4 days 04:42:13,1.0,completed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,NaT,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,False,False,False,False,False,False,False,True,True,11100,Rx with only IBD,2021-10-05 12:36:00-04:00,2021-10-05 12:41:00-04:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-10-22 12:40:36-04:00,NaN,NaN,2021-12-21 03:36:15,MD-BA,2021-10-22 16:40:36,10-21,Oct-21,True,False,True,True,True,True,False,False,False,2021-10-05 16:41:00,4 days 06:09:14,4 days,days,0 days 06:09:14,2021-10-10 15:30:09,0 days 00:05:00,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NA,NA,NA,NA,-13 days +17:15:47,0 days 16:39:55,12 days 06:44:13,NaT,NaT,NaT,NA,NA,NaT,NaT,0 days 01:27:01,4 days 04:42:13,NaT,NaT,NaT,0 days 00:00:00,0 days 00:00:00,0.0,False,True,NB,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352963,352963,MD-BA,204141-0,1871905810.0,67877062690,F,13128,NaT,2021-07-02 11:52:00,2021-07-02 11:52:00,2021-10-16 11:52:08,NaT,NaN,NaT,NaT,NaT,2021-10-16 01:23:40,MD-BA-204141-0,2143674.0,NaT,NaT,2021-07-02 11:52:17,2021-10-15 17:00:10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-07-30 14:29:25,2021-10-06 11:53:12,NaN,2021-10-06 10:13:44,2021-07-23 13:42:26,NaN,2021-07-16 15:20:52,2021-07-23 13:42:26,NaN,NaN,NaN,False,U->F,F,NaN,NaN,NaN,->N,N,IBD NOT POSSIBLE,IBD SPECIALITY,2021-10-15 17:00:08,2021-07-02 11:55:19,NaT,2021-07-30 14:29:26,0 days 00:17:39,1.0,completed,0 days 02:30:32,1.0,completed,NaT,NaN,NaN,14 days 03:25:34,1.0,completed,6 days 22:21:34,1.0,completed,7 days 00:46:59,1.0,completed,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,NaT,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True,True,True,False,False,False,False,False,False,False,True,True,1100,Rx with IBD and CFI both,NaN,2021-07-02 07:52:00-04:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-10-16 07:52:08-04:00,NaN,NaN,2021-12-21 03:36:15,MD-BA,2021-10-16 11:52:08,10-21,Oct-21,True,True,False,True,True,True,True,True,True,2021-07-02 11:52:00,0 days 02:48:11,0 days,days,0 days 02:48:11,2021-07-30 17:17:37,NA,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NA,NA,NA,NA,NaT,28 days 02:37:26,NaT,NaT,0 days 00:03:19,NaT,NA,NA,NaT,NaT,0 days 02:48:11,NaT,14 days 03:25:34,6 days 22:21:34,7 days 00:46:59,28 days 02:34:07,28 days 02:34:07,2428447.0,True,False,NB,NaN
354010,354010,MD-BA,203569-0,1205896727.0,72626260101,F,12890,NaT,2021-06-24 12:31:00,2021-06-24 12:31:00,2021-09-23 00:00:00,NaT,NaN,NaT,NaT,NaT,2021-09-29 01:29:16,MD-BA-203569-0,2143674.0,NaT,NaT,2021-06-24 12:32:01,2021-09-23 16:36:57,2021-07-15 15:59:04,NaN,NaN,NaN,NaN,NaN,NaN,2021-06-30 17:27:51,2021-08-26 16:32:20,NaN,2021-06-25 10:00:39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,U->F,F,NaN,NaN,NaN,->N,N,IBD DENIED CALL MD TO SWITCH,NaN,2021-09-23 16:36:57,NaT,2021-08-26 16:32:21,2021-06-24 12:32:12,0 days 01:10:08,1.0,completed,12 days 17:05:01,1.0,completed,46 days 06:34:43,4.0,completed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,NaT,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True,True,True,False,False,False,False,False,False,False,True,True,1100,Rx with only IBD,NaN,2021-06-24 08:31:00-04:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-09-22 20:00:00-04:00,NaN,NaN,2021-12-21 03:36:15,MD-BA,2021-09-23 00:00:00,09-21,Sep-21,True,False,True,True,True,True,False,False,False,2021-06-24 12:31:00,59 days 00:49:52,59 days,days,0 days 00:49:52,2021-08-22 13:22:04,NA,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NA,NA,NA,NA,-64 days +19:59:51,0 days 00:01:12,63 days 04:00:09,NaT,NaT,NaT,NA,NA,NaT,NaT,12 days 18:15:09,46 days 06:34:43,NaT,NaT,NaT,0 days 00:00:00,0 days 00:00:00,0.0,False,True,NB,NaN

In [63]:
Rx_with_IBD_value_greater_2k_denied_count_pivot = pd.pivot_table(Rx_with_IBD_value_greater_2k_denied, values = ['rx_code_key_location'], index = ['pharmacy_loc'], aggfunc = 'count').reset_index()
Rx_with_IBD_value_greater_2k_denied_count_pivot.rename(columns = {'rx_code_key_location':'rx_count_IBD_Denied'}, inplace = True)
Rx_with_IBD_value_greater_2k_denied_count_pivot

  pharmacy_loc  rx_count_IBD_Denied
0        MD-BA                   70
1        NJ-SO                    7
2        NY-BK                   10
3        NY-MA                    6
4        PA-PH                   12

In [64]:
Rx_with_IBD_value_greater_2k_denied_revenue_pivot = pd.pivot_table(Rx_with_IBD_value_greater_2k_denied, values = ['rx_revenue'], index = ['pharmacy_loc'], aggfunc = 'sum').reset_index()
Rx_with_IBD_value_greater_2k_denied_revenue_pivot.rename(columns = {'rx_revenue':'rx_revenue_IBD_Denied'}, inplace = True)
Rx_with_IBD_value_greater_2k_denied_revenue_pivot

  pharmacy_loc  rx_revenue_IBD_Denied
0        MD-BA                   0.00
1        NJ-SO                3508.00
2        NY-BK                6317.48
3        NY-MA                   0.00
4        PA-PH                   0.00

In [65]:
Rx_with_IBD_value_greater_2k_denied_pivot = pd.merge(Rx_with_IBD_value_greater_2k_denied_count_pivot, Rx_with_IBD_value_greater_2k_denied_revenue_pivot, on='pharmacy_loc', how='left')
Rx_with_IBD_value_greater_2k_denied_pivot

  pharmacy_loc  rx_count_IBD_Denied  rx_revenue_IBD_Denied
0        MD-BA                   70                   0.00
1        NJ-SO                    7                3508.00
2        NY-BK                   10                6317.48
3        NY-MA                    6                   0.00
4        PA-PH                   12                   0.00

In [66]:
Rx_with_IBD_value_greater_2k_denied_pivot.append(Rx_with_IBD_value_greater_2k_denied_pivot.sum(axis=0), ignore_index=True).to_clipboard(index=False)

# IBD not possible

In [67]:
ibd_possible_list = ['TO BE BILLED', 'CALL FOR INS', 'CALL MD (SEE NOTES)',
       'SPEAK WITH INSURANCE', 
        'IBD IS 2K+',
       'IBD IN PROCESS â€“ DARSHI', 'IBD IN PROCESS - MITCHELL', '0',
       'HIV', 'HORIZON-BILL', 'HORIZON-CALL', 'O/O', 'IBD IS $2K+',
       'IBD IN PROCESS - DANIEL', 'COPAY COUNSELING (SEE NOTES)',
       'CALL FOR INS DAY 2', 'COMPLICATED RX ( SEE NOTES)',
       'REFIL-CALLING', 'SALES-FOLLOWUP', 'HORIZON-OK TO BILL',
       'COUPON BILL', 'IBD DONE BY MD', 'SPEAK WITH INS',
       'IBD IN PROCESS - KARIM', 'IBD CHART NOTES REQ - 2K+',
       'DELIVER TO MD OFFICE', 'IBD CHART NOTES REQ - TIARA',
        'COMPLICATED RX (NOTES)',
       'COPAY SPECIALTY', 'DERM GROUP', 'CALL MD TO SWITCH',
       'REFILL CALLING OPTUMRX', 'IBD REQUIRED', 'DE-PD DERMATOLOGY',
       'IBD IN PROCESS - DARSHI', 'IBD IN PROCESS - KATHERINE',
       'NEW PX APP', 'CALL MD TO SWITCH-ACCT. MGT', 'RH-I RHEUMATOLOGY',
       'HUMIRA NURSE AMBASSADOR', 'SMS NRBP 1',
       'COMPLICATED RX (SEE NOTES)', 'IBD CHART NOTES REQ- CHRISTINE',
       "WORKER'S COMP", 'IBD FIDELIS', 'IBD IN PROCESS - TAMIKAH',
       'CX LANGUAGE SPANISH', 'IBD IN PROCESS - CHIARA',
       'REFILL-CALLING OPTUMRX', 'IBD IN PROCESS - ASHLEY',
       'COPAY COUNSELLING', 'IBD CHART NOTES REQ',
       'IBD IN PROCESS - TATYANNA', 'DEL REVERSALS']

In [68]:
Rx_with_IBD_value_less_2k_possible = Rx_with_IBD_value_less_2k[Rx_with_IBD_value_less_2k['trackrx_last_ibdtag'].isin(ibd_possible_list)]

In [69]:
Rx_with_IBD_value_less_2k_possible_count_pivot = pd.pivot_table(Rx_with_IBD_value_less_2k_possible, values = ['rx_code_key_location'], index = ['pharmacy_loc'], aggfunc = 'count').reset_index()
Rx_with_IBD_value_less_2k_possible_count_pivot.rename(columns = {'rx_code_key_location':'rx_count_IBD_Denied'}, inplace = True)
Rx_with_IBD_value_less_2k_possible_count_pivot

  pharmacy_loc  rx_count_IBD_Denied
0        FL-MI                 1467
1        MD-BA                 2110
2        NC-RA                  820
3        NJ-SO                 7515
4        NY-BK                 8412
5        NY-MA                  732
6        PA-PH                 3319

In [70]:
Rx_with_IBD_value_less_2k_possible_revenue_pivot = pd.pivot_table(Rx_with_IBD_value_less_2k_possible, values = ['rx_revenue'], index = ['pharmacy_loc'], aggfunc = 'sum').reset_index()
Rx_with_IBD_value_less_2k_possible_revenue_pivot.rename(columns = {'rx_revenue':'rx_revenue_IBD_Denied'}, inplace = True)
Rx_with_IBD_value_less_2k_possible_revenue_pivot

  pharmacy_loc  rx_revenue_IBD_Denied
0        FL-MI              682127.59
1        MD-BA             1500452.61
2        NC-RA              549378.27
3        NJ-SO             4135245.01
4        NY-BK             3763806.46
5        NY-MA              107765.63
6        PA-PH             1832997.26

In [71]:
Rx_with_IBD_value_less_2k_possible_pivot = pd.merge(Rx_with_IBD_value_less_2k_possible_count_pivot, Rx_with_IBD_value_less_2k_possible_revenue_pivot, on='pharmacy_loc', how='left')
Rx_with_IBD_value_less_2k_possible_pivot

  pharmacy_loc  rx_count_IBD_Denied  rx_revenue_IBD_Denied
0        FL-MI                 1467              682127.59
1        MD-BA                 2110             1500452.61
2        NC-RA                  820              549378.27
3        NJ-SO                 7515             4135245.01
4        NY-BK                 8412             3763806.46
5        NY-MA                  732              107765.63
6        PA-PH                 3319             1832997.26

In [72]:
Rx_with_IBD_value_less_2k_possible_pivot.append(Rx_with_IBD_value_less_2k_possible_pivot.sum(axis=0), ignore_index=True).to_clipboard(index=False)

In [73]:
### Rx_with_IBD_value_greater_2k_possible

In [74]:
Rx_with_IBD_value_greater_2k_possible = Rx_with_IBD_value_greater_2k[Rx_with_IBD_value_greater_2k['trackrx_last_ibdtag'].isin(ibd_possible_list)]

In [75]:
Rx_with_IBD_value_greater_2k_possible_count_pivot = pd.pivot_table(Rx_with_IBD_value_greater_2k_possible, values = ['rx_code_key_location'], index = ['pharmacy_loc'], aggfunc = 'count').reset_index()
Rx_with_IBD_value_greater_2k_possible_count_pivot.rename(columns = {'rx_code_key_location':'rx_count_IBD_possible'}, inplace = True)
Rx_with_IBD_value_greater_2k_possible_count_pivot

  pharmacy_loc  rx_count_IBD_possible
0        MD-BA                    396
1        NC-RA                     31
2        NJ-SO                    299
3        NY-BK                    732
4        NY-MA                     46
5        PA-PH                    538

In [76]:
Rx_with_IBD_value_greater_2k_possible_revenue_pivot = pd.pivot_table(Rx_with_IBD_value_greater_2k_possible, values = ['rx_revenue'], index = ['pharmacy_loc'], aggfunc = 'sum').reset_index()
Rx_with_IBD_value_greater_2k_possible_revenue_pivot.rename(columns = {'rx_revenue':'rx_revenue_IBD_possible'}, inplace = True)
Rx_with_IBD_value_greater_2k_possible_revenue_pivot

  pharmacy_loc  rx_revenue_IBD_possible
0        MD-BA                508055.15
1        NC-RA                 67870.72
2        NJ-SO                351809.81
3        NY-BK               1424343.98
4        NY-MA                  9107.78
5        PA-PH                396840.72

In [77]:
Rx_with_IBD_value_greater_2k_denied_pivot = pd.merge(Rx_with_IBD_value_greater_2k_possible_count_pivot, Rx_with_IBD_value_greater_2k_possible_revenue_pivot, on='pharmacy_loc', how='left')
Rx_with_IBD_value_greater_2k_denied_pivot

  pharmacy_loc  rx_count_IBD_possible  rx_revenue_IBD_possible
0        MD-BA                    396                508055.15
1        NC-RA                     31                 67870.72
2        NJ-SO                    299                351809.81
3        NY-BK                    732               1424343.98
4        NY-MA                     46                  9107.78
5        PA-PH                    538                396840.72

In [78]:
Rx_with_IBD_value_greater_2k_denied_pivot.append(Rx_with_IBD_value_greater_2k_denied_pivot.sum(axis=0), ignore_index=True).to_clipboard(index=False)

# IBD billed & unbilled

In [79]:
# Rx_with_IBD_value_less_2k_denied
# Rx_with_IBD_value_greater_2k_denied
# Rx_with_IBD_value_less_2k_possible
# Rx_with_IBD_value_greater_2k_possible

In [80]:
# Rx_with_IBD_value_less_2k_denied billed & unbilled

In [81]:
Rx_with_IBD_value_less_2k_denied_billed = Rx_with_IBD_value_less_2k_denied[Rx_with_IBD_value_less_2k_denied['trackrx_last_status_new']=='B']

In [82]:
Rx_with_IBD_value_less_2k_denied_billed_count_pivot = pd.pivot_table(Rx_with_IBD_value_less_2k_denied_billed, values = ['rx_code_key_location'], index = ['pharmacy_loc'], aggfunc = 'count').reset_index()
Rx_with_IBD_value_less_2k_denied_billed_count_pivot.rename(columns = {'pharmacy_loc': 'pharmacy loc', 'rx_code_key_location':'Rx count for IBD < 2k'}, inplace = True)
#Rx_with_IBD_value_less_2k_denied_billed_count_pivot

Rx_with_IBD_value_less_2k_denied_billed_revenue_pivot = pd.pivot_table(Rx_with_IBD_value_less_2k_denied_billed, values = ['rx_revenue'], index = ['pharmacy_loc'], aggfunc = 'sum').reset_index()
Rx_with_IBD_value_less_2k_denied_billed_revenue_pivot.rename(columns = {'pharmacy_loc': 'pharmacy loc', 'rx_revenue':'Rx revenue for IBD < 2k($)'}, inplace = True)
#Rx_with_IBD_value_less_2k_denied_billed_revenue_pivot

Rx_with_IBD_value_less_2k_denied_billed_pivot = pd.merge(Rx_with_IBD_value_less_2k_denied_billed_count_pivot, Rx_with_IBD_value_less_2k_denied_billed_revenue_pivot, on='pharmacy loc', how='left')
Rx_with_IBD_value_less_2k_denied_billed_pivot

  pharmacy loc  Rx count for IBD < 2k  Rx revenue for IBD < 2k($)
0        FL-MI                     19                    12487.93
1        MD-BA                      1                       83.28
2        NY-BK                     51                    11940.17
3        PA-PH                     24                    30916.06

In [83]:
Rx_with_IBD_value_less_2k_denied_billed_pivot.append(Rx_with_IBD_value_less_2k_denied_billed_pivot.sum(axis=0), ignore_index=True).to_clipboard(index=False)

In [84]:
# Rx_with_IBD_value_less_2k_denied_unbilled

In [85]:
Rx_with_IBD_value_less_2k_denied_unbilled = Rx_with_IBD_value_less_2k_denied[Rx_with_IBD_value_less_2k_denied['trackrx_last_status_new']=='NB']

In [86]:
Rx_with_IBD_value_less_2k_denied_unbilled_count_pivot = pd.pivot_table(Rx_with_IBD_value_less_2k_denied_unbilled, values = ['rx_code_key_location'], index = ['pharmacy_loc'], aggfunc = 'count').reset_index()
Rx_with_IBD_value_less_2k_denied_unbilled_count_pivot.rename(columns = {'rx_code_key_location':'rx_count_IBD_Denied_unbilled'}, inplace = True)
#Rx_with_IBD_value_less_2k_denied_unbilled_count_pivot

Rx_with_IBD_value_less_2k_denied_unbilled_revenue_pivot = pd.pivot_table(Rx_with_IBD_value_less_2k_denied_unbilled, values = ['rx_revenue'], index = ['pharmacy_loc'], aggfunc = 'sum').reset_index()
Rx_with_IBD_value_less_2k_denied_unbilled_revenue_pivot.rename(columns = {'rx_revenue':'rx_revenue_IBD_Denied_unbilled'}, inplace = True)
#Rx_with_IBD_value_less_2k_denied_unbilled_revenue_pivot

Rx_with_IBD_value_less_2k_denied_unbilled_pivot = pd.merge(Rx_with_IBD_value_less_2k_denied_unbilled_count_pivot, Rx_with_IBD_value_less_2k_denied_unbilled_revenue_pivot, on='pharmacy_loc', how='left')
Rx_with_IBD_value_less_2k_denied_unbilled_pivot

  pharmacy_loc  rx_count_IBD_Denied_unbilled  rx_revenue_IBD_Denied_unbilled
0        FL-MI                            84                            0.00
1        MD-BA                           611                         6641.35
2        NC-RA                             7                            0.00
3        NJ-SO                            67                         3508.00
4        NY-BK                           102                         6402.23
5        NY-MA                           120                            0.00
6        PA-PH                           199                         7338.48

In [87]:
Rx_with_IBD_value_less_2k_denied_unbilled_pivot.append(Rx_with_IBD_value_less_2k_denied_unbilled_pivot.sum(axis=0), ignore_index=True).to_clipboard(index=False)

In [88]:
### Rx_with_IBD_value_less_2k_possible billed & unbilled

In [89]:
Rx_with_IBD_value_less_2k_possible_billed = Rx_with_IBD_value_less_2k_possible[Rx_with_IBD_value_less_2k_possible['trackrx_last_status_new']=='B']

In [90]:
Rx_with_IBD_value_less_2k_possible_billed_count_pivot = pd.pivot_table(Rx_with_IBD_value_less_2k_possible_billed, values = ['rx_code_key_location'], index = ['pharmacy_loc'], aggfunc = 'count').reset_index()
Rx_with_IBD_value_less_2k_possible_billed_count_pivot.rename(columns = {'pharmacy_loc': 'pharmacy loc', 'rx_code_key_location':'Rx count for IBD < 2k'}, inplace = True)
#Rx_with_IBD_value_less_2k_possible_billed_count_pivot

Rx_with_IBD_value_less_2k_possible_billed_revenue_pivot = pd.pivot_table(Rx_with_IBD_value_less_2k_possible_billed, values = ['rx_revenue'], index = ['pharmacy_loc'], aggfunc = 'sum').reset_index()
Rx_with_IBD_value_less_2k_possible_billed_revenue_pivot.rename(columns = {'pharmacy_loc': 'pharmacy loc', 'rx_revenue':'Rx revenue for IBD < 2k($)'}, inplace = True)
#Rx_with_IBD_value_less_2k_possible_billed_revenue_pivot

Rx_with_IBD_value_less_2k_possible_billed_pivot = pd.merge(Rx_with_IBD_value_less_2k_possible_billed_count_pivot, Rx_with_IBD_value_less_2k_possible_billed_revenue_pivot, on='pharmacy loc', how='left')
Rx_with_IBD_value_less_2k_possible_billed_pivot

  pharmacy loc  Rx count for IBD < 2k  Rx revenue for IBD < 2k($)
0        FL-MI                    470                   673837.46
1        MD-BA                    753                  1395154.09
2        NC-RA                    314                   547291.52
3        NJ-SO                   2847                  3961927.36
4        NY-BK                   2961                  3506778.32
5        NY-MA                    321                   106560.88
6        PA-PH                    966                  1687303.35

In [91]:
Rx_with_IBD_value_less_2k_possible_billed_pivot.append(Rx_with_IBD_value_less_2k_possible_billed_pivot.sum(axis=0), ignore_index=True).to_clipboard(index=False)

In [92]:
Rx_with_IBD_value_less_2k_possible_unbilled = Rx_with_IBD_value_less_2k_possible[Rx_with_IBD_value_less_2k_possible['trackrx_last_status_new']=='NB']

In [93]:
Rx_with_IBD_value_less_2k_possible_unbilled_count_pivot = pd.pivot_table(Rx_with_IBD_value_less_2k_possible_unbilled, values = ['rx_code_key_location'], index = ['pharmacy_loc'], aggfunc = 'count').reset_index()
Rx_with_IBD_value_less_2k_possible_unbilled_count_pivot.rename(columns = {'rx_code_key_location':'rx_count_IBD_possible_unbilled'}, inplace = True)

Rx_with_IBD_value_less_2k_possible_unbilled_revenue_pivot = pd.pivot_table(Rx_with_IBD_value_less_2k_possible_unbilled, values = ['rx_revenue'], index = ['pharmacy_loc'], aggfunc = 'sum').reset_index()
Rx_with_IBD_value_less_2k_possible_unbilled_revenue_pivot.rename(columns = {'rx_revenue':'rx_revenue_IBD_possible_unbilled'}, inplace = True)

Rx_with_IBD_value_less_2k_possible_unbilled_pivot = pd.merge(Rx_with_IBD_value_less_2k_possible_unbilled_count_pivot, Rx_with_IBD_value_less_2k_possible_unbilled_revenue_pivot, on='pharmacy_loc', how='left')
Rx_with_IBD_value_less_2k_possible_unbilled_pivot

,pharmacy_loc,rx_count_IBD_possible_unbilled,rx_revenue_IBD_possible_unbilled
0,FL-MI,997,8290.13
1,MD-BA,1357,105298.52
2,NC-RA,506,2086.75
3,NJ-SO,4668,173317.65
4,NY-BK,5451,257028.14
5,NY-MA,411,1204.75
6,PA-PH,2353,145693.91

In [94]:
Rx_with_IBD_value_less_2k_possible_unbilled_pivot.append(Rx_with_IBD_value_less_2k_possible_unbilled_pivot.sum(axis=0), ignore_index=True).to_clipboard(index=False)

In [95]:
## Rx_with_IBD_value_greater_2k_denied billed & unbilled

In [96]:
Rx_with_IBD_value_greater_2k_denied_billed = Rx_with_IBD_value_greater_2k_denied[Rx_with_IBD_value_greater_2k_denied['trackrx_last_status_new']=='B']

In [97]:
Rx_with_IBD_value_greater_2k_denied_billed_count_pivot = pd.pivot_table(Rx_with_IBD_value_greater_2k_denied_billed, values = ['rx_code_key_location'], index = ['pharmacy_loc'], aggfunc = 'count').reset_index()
Rx_with_IBD_value_greater_2k_denied_billed_count_pivot.rename(columns = {'pharmacy_loc': 'pharmacy loc','rx_code_key_location':'Rx count for IBD > 2k'}, inplace = True)
#Rx_with_IBD_value_greater_2k_denied_billed_count_pivot

Rx_with_IBD_value_greater_2k_denied_billed_revenue_pivot = pd.pivot_table(Rx_with_IBD_value_greater_2k_denied_billed, values = ['rx_revenue'], index = ['pharmacy_loc'], aggfunc = 'sum').reset_index()
Rx_with_IBD_value_greater_2k_denied_billed_revenue_pivot.rename(columns = {'pharmacy_loc': 'pharmacy loc','rx_revenue':'Rx revenue for IBD > 2k($)'}, inplace = True)
#Rx_with_IBD_value_greater_2k_denied_billed_revenue_pivot

Rx_with_IBD_value_greater_2k_denied_billed_pivot = pd.merge(Rx_with_IBD_value_greater_2k_denied_billed_count_pivot, Rx_with_IBD_value_greater_2k_denied_billed_revenue_pivot, on='pharmacy loc', how='left')
Rx_with_IBD_value_greater_2k_denied_billed_pivot

  pharmacy loc  Rx count for IBD > 2k  Rx revenue for IBD > 2k($)
0        NY-BK                      1                       14.58

In [98]:
Rx_with_IBD_value_greater_2k_denied_unbilled = Rx_with_IBD_value_greater_2k_denied[Rx_with_IBD_value_greater_2k_denied['trackrx_last_status_new']=='NB']

In [99]:
Rx_with_IBD_value_greater_2k_denied_unbilled_count_pivot = pd.pivot_table(Rx_with_IBD_value_greater_2k_denied_unbilled, values = ['rx_code_key_location'], index = ['pharmacy_loc'], aggfunc = 'count').reset_index()
Rx_with_IBD_value_greater_2k_denied_unbilled_count_pivot.rename(columns = {'rx_code_key_location':'rx_count_IBD_denied_unbilled'}, inplace = True)

Rx_with_IBD_value_greater_2k_denied_unbilled_revenue_pivot = pd.pivot_table(Rx_with_IBD_value_greater_2k_denied_unbilled, values = ['rx_revenue'], index = ['pharmacy_loc'], aggfunc = 'sum').reset_index()
Rx_with_IBD_value_greater_2k_denied_unbilled_revenue_pivot.rename(columns = {'rx_revenue':'rx_revenue_IBD_denied_unbilled'}, inplace = True)

Rx_with_IBD_value_greater_2k_denied_unbilled_pivot = pd.merge(Rx_with_IBD_value_greater_2k_denied_unbilled_count_pivot, Rx_with_IBD_value_greater_2k_denied_unbilled_revenue_pivot, on='pharmacy_loc', how='left')
Rx_with_IBD_value_greater_2k_denied_unbilled_pivot

  pharmacy_loc  rx_count_IBD_denied_unbilled  rx_revenue_IBD_denied_unbilled
0        MD-BA                            70                             0.0
1        NJ-SO                             7                          3508.0
2        NY-BK                             9                          6302.9
3        NY-MA                             6                             0.0
4        PA-PH                            12                             0.0

In [100]:
Rx_with_IBD_value_greater_2k_denied_unbilled_pivot.append(Rx_with_IBD_value_greater_2k_denied_unbilled_pivot.sum(axis=0),ignore_index=True).to_clipboard(index=False)

In [101]:
## Rx_with_IBD_value_greater_2k_possible billed & unbilled

In [102]:
Rx_with_IBD_value_greater_2k_possible_billed = Rx_with_IBD_value_greater_2k_possible[Rx_with_IBD_value_greater_2k_possible['trackrx_last_status_new']=='B']

In [103]:
Rx_with_IBD_value_greater_2k_possible_billed_count_pivot = pd.pivot_table(Rx_with_IBD_value_greater_2k_possible_billed, values = ['rx_code_key_location'], index = ['pharmacy_loc'], aggfunc = 'count').reset_index()
Rx_with_IBD_value_greater_2k_possible_billed_count_pivot.rename(columns = {'pharmacy_loc':'pharmacy loc','rx_code_key_location':'Rx count for IBD > 2k'}, inplace = True)
#Rx_with_IBD_value_greater_2k_possible_billed_count_pivot

Rx_with_IBD_value_greater_2k_possible_billed_revenue_pivot = pd.pivot_table(Rx_with_IBD_value_greater_2k_possible_billed, values = ['rx_revenue'], index = ['pharmacy_loc'], aggfunc = 'sum').reset_index()
Rx_with_IBD_value_greater_2k_possible_billed_revenue_pivot.rename(columns = {'pharmacy_loc':'pharmacy loc', 'rx_revenue':'Rx revenue for IBD > 2k($)'}, inplace = True)
#Rx_with_IBD_value_greater_2k_possible_billed_revenue_pivot

Rx_with_IBD_value_greater_2k_possible_billed_pivot = pd.merge(Rx_with_IBD_value_greater_2k_possible_billed_count_pivot, Rx_with_IBD_value_greater_2k_possible_billed_revenue_pivot, on='pharmacy loc', how='left')
Rx_with_IBD_value_greater_2k_possible_billed_pivot

  pharmacy loc  Rx count for IBD > 2k  Rx revenue for IBD > 2k($)
0        MD-BA                    101                   442298.93
1        NC-RA                     10                    67870.72
2        NJ-SO                     78                   329115.35
3        NY-BK                    294                  1302577.55
4        NY-MA                     10                     9107.78
5        PA-PH                     88                   272622.19

In [104]:
Rx_with_IBD_value_greater_2k_possible_billed_pivot.append(Rx_with_IBD_value_greater_2k_possible_billed_pivot.sum(axis=0),ignore_index=True).to_clipboard(index=False)

In [105]:
Rx_with_IBD_value_greater_2k_possible_unbilled = Rx_with_IBD_value_greater_2k_possible[Rx_with_IBD_value_greater_2k_possible['trackrx_last_status_new']=='NB']

In [106]:
Rx_with_IBD_value_greater_2k_possible_unbilled_count_pivot = pd.pivot_table(Rx_with_IBD_value_greater_2k_possible_unbilled, values = ['rx_code_key_location'], index = ['pharmacy_loc'], aggfunc = 'count').reset_index()
Rx_with_IBD_value_greater_2k_possible_unbilled_count_pivot.rename(columns = {'rx_code_key_location':'rx_count_IBD_possible_unbilled'}, inplace = True)

Rx_with_IBD_value_greater_2k_possible_unbilled_revenue_pivot = pd.pivot_table(Rx_with_IBD_value_greater_2k_possible_unbilled, values = ['rx_revenue'], index = ['pharmacy_loc'], aggfunc = 'sum').reset_index()
Rx_with_IBD_value_greater_2k_possible_unbilled_revenue_pivot.rename(columns = {'rx_revenue':'rx_revenue_IBD_possible_unbilled'}, inplace = True)

Rx_with_IBD_value_greater_2k_possible_unbilled_pivot = pd.merge(Rx_with_IBD_value_greater_2k_possible_unbilled_count_pivot, Rx_with_IBD_value_greater_2k_possible_unbilled_revenue_pivot, on='pharmacy_loc', how='left')
Rx_with_IBD_value_greater_2k_possible_unbilled_pivot

,pharmacy_loc,rx_count_IBD_possible_unbilled,rx_revenue_IBD_possible_unbilled
0,MD-BA,295,65756.22
1,NC-RA,21,0.00
2,NJ-SO,221,22694.46
3,NY-BK,438,121766.43
4,NY-MA,36,0.00
5,PA-PH,450,124218.53

In [107]:
#final data frames for Count & Revenue

# IBD denied count

Rx_with_IBD_value_greater_2k_possible_unbilled_pivot.append(Rx_with_IBD_value_greater_2k_possible_unbilled_pivot.sum(axis=0),ignore_index=True)

Rx_with_IBD_value_less_2k_denied_billed_count_pivot

IBD_denied_count_less_and_greater_than_2k = pd.merge(Rx_with_IBD_value_less_2k_denied_billed_count_pivot, Rx_with_IBD_value_greater_2k_denied_billed_count_pivot, on = 'pharmacy loc', how = 'outer')
# print(IBD_denied_count_less_and_greater_than_2k)

IBD_denied_count_less_and_greater_than_2k = IBD_denied_count_less_and_greater_than_2k.append(IBD_denied_count_less_and_greater_than_2k.sum(axis = 0), ignore_index = True)
IBD_denied_count_less_and_greater_than_2k.iloc[[len(IBD_denied_count_less_and_greater_than_2k)-1],[0]] = 'Overall'
IBD_denied_count_less_and_greater_than_2k = IBD_denied_count_less_and_greater_than_2k.fillna(0)
IBD_denied_count_less_and_greater_than_2k = IBD_denied_count_less_and_greater_than_2k.set_index('pharmacy loc')
IBD_denied_count_less_and_greater_than_2k = IBD_denied_count_less_and_greater_than_2k[IBD_denied_count_less_and_greater_than_2k.columns[:]].div(6,0).astype(int)
IBD_denied_count_less_and_greater_than_2k

#IBD_denied_count_less_and_greater_than_2k = IBD_denied_count_less_and_greater_than_2k.fillna(0)
#IBD_denied_count_less_and_greater_than_2k = IBD_denied_count_less_and_greater_than_2k.set_index('pharmacy loc')
IBD_denied_count_less_and_greater_than_2k['Total Count'] = IBD_denied_count_less_and_greater_than_2k[['Rx count for IBD < 2k', 'Rx count for IBD > 2k']].sum(axis=1)
IBD_denied_count_less_and_greater_than_2k

IBD_denied_count_less_and_greater_than_2k['Rx count for IBD < 2k %'] = round(IBD_denied_count_less_and_greater_than_2k['Rx count for IBD < 2k']/IBD_denied_count_less_and_greater_than_2k['Total Count']*100,0).astype(int)
IBD_denied_count_less_and_greater_than_2k['Rx count for IBD > 2k %'] = round(IBD_denied_count_less_and_greater_than_2k['Rx count for IBD > 2k']/IBD_denied_count_less_and_greater_than_2k['Total Count']*100,0).astype(int)

IBD_denied_count_less_and_greater_than_2k_final = IBD_denied_count_less_and_greater_than_2k[['Total Count', 'Rx count for IBD < 2k', 'Rx count for IBD < 2k %', 'Rx count for IBD > 2k', 'Rx count for IBD > 2k %']]
#IBD_denied_count_less_and_greater_than_2k_final = IBD_denied_count_less_and_greater_than_2k_final.set_index('pharmacy loc')
IBD_denied_count_less_and_greater_than_2k_final = IBD_denied_count_less_and_greater_than_2k_final.rename(columns = {'Rx count for IBD < 2k %': ' %', 'Rx count for IBD > 2k %': '% '})
IBD_denied_count_less_and_greater_than_2k_final

for i in IBD_denied_count_less_and_greater_than_2k_final.columns:
    IBD_denied_count_less_and_greater_than_2k_final[i] = IBD_denied_count_less_and_greater_than_2k_final[i].astype(int)

subset_value = (IBD_denied_count_less_and_greater_than_2k_final.index.to_list()[:-1], ['Rx count for IBD < 2k', 'Rx count for IBD > 2k'])
df_style3 = IBD_denied_count_less_and_greater_than_2k_final.style.set_properties(**{'text-align': 'center','border-color':'white','border-width':'thin','border-style':'solid'}).background_gradient(cmap='RdYlGn',axis=1, subset = subset_value).format("{:,}")
df_style3

# dfi.export(df_style3, ibd_images+'ibd_denied_count_less_and_greater_than_2k_final.png')

# IBD denied revenue

IBD_denied_revenue_less_and_greater_than_2k = pd.merge(Rx_with_IBD_value_less_2k_denied_billed_revenue_pivot, Rx_with_IBD_value_greater_2k_denied_billed_revenue_pivot, on = 'pharmacy loc', how = 'outer')
IBD_denied_revenue_less_and_greater_than_2k = IBD_denied_revenue_less_and_greater_than_2k.append(IBD_denied_revenue_less_and_greater_than_2k.sum(axis = 0), ignore_index = True)
IBD_denied_revenue_less_and_greater_than_2k.iloc[[len(IBD_denied_revenue_less_and_greater_than_2k)-1],[0]] = 'Overall'
IBD_denied_revenue_less_and_greater_than_2k = IBD_denied_revenue_less_and_greater_than_2k.fillna(0)
IBD_denied_revenue_less_and_greater_than_2k = IBD_denied_revenue_less_and_greater_than_2k.set_index('pharmacy loc')
IBD_denied_revenue_less_and_greater_than_2k = IBD_denied_revenue_less_and_greater_than_2k.astype(int)
IBD_denied_revenue_less_and_greater_than_2k = IBD_denied_revenue_less_and_greater_than_2k[IBD_denied_revenue_less_and_greater_than_2k.columns[:]].div(6,0).astype(int)
IBD_denied_revenue_less_and_greater_than_2k

IBD_denied_revenue_less_and_greater_than_2k['Total Revenue($)'] = IBD_denied_revenue_less_and_greater_than_2k[['Rx revenue for IBD < 2k($)', 'Rx revenue for IBD > 2k($)']].sum(axis=1)
IBD_denied_revenue_less_and_greater_than_2k['Rx revenue for IBD < 2k %'] = round(IBD_denied_revenue_less_and_greater_than_2k['Rx revenue for IBD < 2k($)']/IBD_denied_revenue_less_and_greater_than_2k['Total Revenue($)']*100,0).astype(int)
IBD_denied_revenue_less_and_greater_than_2k['Rx revenue for IBD > 2k %'] = round(IBD_denied_revenue_less_and_greater_than_2k['Rx revenue for IBD > 2k($)']/IBD_denied_revenue_less_and_greater_than_2k['Total Revenue($)']*100,0).astype(int)
IBD_denied_revenue_less_and_greater_than_2k

IBD_denied_revenue_less_and_greater_than_2k_final = IBD_denied_revenue_less_and_greater_than_2k[['Total Revenue($)', 'Rx revenue for IBD < 2k($)', 'Rx revenue for IBD < 2k %', 'Rx revenue for IBD > 2k($)', 'Rx revenue for IBD > 2k %']]
#IBD_denied_revenue_less_and_greater_than_2k_final = IBD_denied_revenue_less_and_greater_than_2k_final.set_index('pharmacy loc')
IBD_denied_revenue_less_and_greater_than_2k_final = IBD_denied_revenue_less_and_greater_than_2k_final.rename(columns = {'Rx revenue for IBD < 2k %': ' %', 'Rx revenue for IBD > 2k %': '% '})
IBD_denied_revenue_less_and_greater_than_2k_final

for i in IBD_denied_revenue_less_and_greater_than_2k_final.columns:
    IBD_denied_revenue_less_and_greater_than_2k_final[i] = IBD_denied_revenue_less_and_greater_than_2k_final[i].astype(int)

subset_value = (IBD_denied_revenue_less_and_greater_than_2k_final.index.to_list()[:-1], ['Rx revenue for IBD < 2k($)', 'Rx revenue for IBD > 2k($)'])
df_style4 = IBD_denied_revenue_less_and_greater_than_2k_final.style.set_properties(**{'text-align': 'center','border-color':'white','border-width':'thin','border-style':'solid'}).background_gradient(cmap='RdYlGn',axis=1, subset = subset_value).format("{:,}")
# dfi.export(df_style4, ibd_images+'ibd_denied_revenue_less_and_greater_than_2k_final.png')
df_style4

# IBD not possible count

IBD_not_possible_count_less_and_greater_than_2k = pd.merge(Rx_with_IBD_value_less_2k_possible_billed_count_pivot, Rx_with_IBD_value_greater_2k_possible_billed_count_pivot, on = 'pharmacy loc', how = 'outer')
IBD_not_possible_count_less_and_greater_than_2k = IBD_not_possible_count_less_and_greater_than_2k.append(IBD_not_possible_count_less_and_greater_than_2k.sum(axis = 0), ignore_index = True)
IBD_not_possible_count_less_and_greater_than_2k = IBD_not_possible_count_less_and_greater_than_2k.fillna(0)
IBD_not_possible_count_less_and_greater_than_2k.iloc[[7],[0]] = 'Overall'
IBD_not_possible_count_less_and_greater_than_2k = IBD_not_possible_count_less_and_greater_than_2k.set_index('pharmacy loc')
IBD_not_possible_count_less_and_greater_than_2k = IBD_not_possible_count_less_and_greater_than_2k[IBD_not_possible_count_less_and_greater_than_2k.columns[:]].div(6,0).astype(int)
IBD_not_possible_count_less_and_greater_than_2k['Total count'] = IBD_not_possible_count_less_and_greater_than_2k[['Rx count for IBD < 2k', 'Rx count for IBD > 2k']].sum(axis=1)
IBD_not_possible_count_less_and_greater_than_2k

#IBD_not_possible_count_less_and_greater_than_2k['Total count'] = IBD_not_possible_count_less_and_greater_than_2k[['Rx count for IBD < 2k', 'Rx count for IBD > 2k']].sum(axis=1)
IBD_not_possible_count_less_and_greater_than_2k['Rx count for IBD < 2k %'] = round(IBD_not_possible_count_less_and_greater_than_2k['Rx count for IBD < 2k']/IBD_not_possible_count_less_and_greater_than_2k['Total count']*100,0).astype(int)
IBD_not_possible_count_less_and_greater_than_2k['Rx count for IBD > 2k %'] = round(IBD_not_possible_count_less_and_greater_than_2k['Rx count for IBD > 2k']/IBD_not_possible_count_less_and_greater_than_2k['Total count']*100,0).astype(int)
IBD_not_possible_count_less_and_greater_than_2k

IBD_not_possible_count_less_and_greater_than_2k_final = IBD_not_possible_count_less_and_greater_than_2k[['Total count', 'Rx count for IBD < 2k', 'Rx count for IBD < 2k %', 'Rx count for IBD > 2k', 'Rx count for IBD > 2k %']]
#IBD_not_possible_count_less_and_greater_than_2k_final = IBD_not_possible_count_less_and_greater_than_2k_final.set_index('pharmacy loc')
IBD_not_possible_count_less_and_greater_than_2k_final = IBD_not_possible_count_less_and_greater_than_2k_final.rename(columns = {'Rx count for IBD < 2k %': ' %', 'Rx count for IBD > 2k %': '% '})
IBD_not_possible_count_less_and_greater_than_2k_final

subset_value = (IBD_not_possible_count_less_and_greater_than_2k_final.index.to_list()[:-1], ['Rx count for IBD < 2k', 'Rx count for IBD > 2k'])
df_style5 = IBD_not_possible_count_less_and_greater_than_2k_final.style.set_properties(**{'text-align': 'center','border-color':'white','border-width':'thin','border-style':'solid'}).background_gradient(cmap='RdYlGn',axis=1, subset = subset_value).format("{:,}")
# dfi.export(df_style5, ibd_images+'ibd_not_possible_count_less_and_greater_than_2k_final.png')
df_style5

# IBD not possible revenue

IBD_not_possible_revenue_less_and_greater_than_2k = pd.merge(Rx_with_IBD_value_less_2k_possible_billed_revenue_pivot, Rx_with_IBD_value_greater_2k_possible_billed_revenue_pivot, on = 'pharmacy loc', how = 'outer')
IBD_not_possible_revenue_less_and_greater_than_2k = IBD_not_possible_revenue_less_and_greater_than_2k.append(IBD_not_possible_revenue_less_and_greater_than_2k.sum(axis = 0), ignore_index = True)
IBD_not_possible_revenue_less_and_greater_than_2k = IBD_not_possible_revenue_less_and_greater_than_2k.fillna(0)
IBD_not_possible_revenue_less_and_greater_than_2k.iloc[[len(IBD_not_possible_revenue_less_and_greater_than_2k)-1],[0]] = 'Overall'

IBD_not_possible_revenue_less_and_greater_than_2k = IBD_not_possible_revenue_less_and_greater_than_2k.set_index('pharmacy loc')
IBD_not_possible_revenue_less_and_greater_than_2k = IBD_not_possible_revenue_less_and_greater_than_2k[IBD_not_possible_revenue_less_and_greater_than_2k.columns[:]].div(6,0).astype(int)
IBD_not_possible_revenue_less_and_greater_than_2k

IBD_not_possible_revenue_less_and_greater_than_2k['Total Revenue ($)'] = IBD_not_possible_revenue_less_and_greater_than_2k[['Rx revenue for IBD < 2k($)', 'Rx revenue for IBD > 2k($)']].sum(axis=1)
IBD_not_possible_revenue_less_and_greater_than_2k['Rx revenue for IBD < 2k %'] = round(IBD_not_possible_revenue_less_and_greater_than_2k['Rx revenue for IBD < 2k($)']/IBD_not_possible_revenue_less_and_greater_than_2k['Total Revenue ($)']*100,0).astype(int)
IBD_not_possible_revenue_less_and_greater_than_2k['Rx revenue for IBD > 2k %'] = round(IBD_not_possible_revenue_less_and_greater_than_2k['Rx revenue for IBD > 2k($)']/IBD_not_possible_revenue_less_and_greater_than_2k['Total Revenue ($)']*100,0).astype(int)
IBD_not_possible_revenue_less_and_greater_than_2k

IBD_not_possible_revenue_less_and_greater_than_2k_final = IBD_not_possible_revenue_less_and_greater_than_2k[['Total Revenue ($)', 'Rx revenue for IBD < 2k($)', 'Rx revenue for IBD < 2k %', 'Rx revenue for IBD > 2k($)', 'Rx revenue for IBD > 2k %']]
#IBD_not_possible_revenue_less_and_greater_than_2k_final = IBD_not_possible_revenue_less_and_greater_than_2k_final.set_index('pharmacy loc')
IBD_not_possible_revenue_less_and_greater_than_2k_final = IBD_not_possible_revenue_less_and_greater_than_2k_final.rename(columns = {'Rx revenue for IBD < 2k %': ' %', 'Rx revenue for IBD > 2k %': '% '})
IBD_not_possible_revenue_less_and_greater_than_2k_final

for i in IBD_not_possible_revenue_less_and_greater_than_2k_final.columns:
    IBD_not_possible_revenue_less_and_greater_than_2k_final[i] = IBD_not_possible_revenue_less_and_greater_than_2k_final[i].astype(int)

subset_value = (IBD_not_possible_revenue_less_and_greater_than_2k_final.index.to_list()[:-1], ['Rx revenue for IBD < 2k($)', 'Rx revenue for IBD > 2k($)'])
df_style6 = IBD_not_possible_revenue_less_and_greater_than_2k_final.style.set_properties(**{'text-align': 'center','border-color':'white','border-width':'thin','border-style':'solid'}).background_gradient(cmap='RdYlGn',axis=1, subset = subset_value).format("{:,}")
# dfi.export(df_style6, ibd_images+'ibd_not_possible_revenue_less_and_greater_than_2k_final.png')
# df_style6